allow-missing-formatter = true

excludes = ["3rdparty/*"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.prettier]
command = "prettier"
includes = ["*.md", "*.mdx"]
options = ["--write"]

[formatter.clang-format]
command = "clang-format"
includes = ["*.cc", "*.hh", "*.c", "*.h"]
options = ["-i"]
