name: Setup environment
description: Setup environment for running workflows.
runs:
  using: "composite"
  steps:
    - name: Compile base version of the static and shared libraries
      shell: sh
      run: make release > build_log
