Mata: Nft Class Reference
Nft Class Reference
A class representing an NFT.
#include <nft.hh>
Public Member Functions
Nft (Delta delta={}, utils::SparseSet< State > initial_states={}, utils::SparseSet< State > final_states={}, Levels levels={}, const size_t num_of_levels=DEFAULT_NUM_OF_LEVELS, Alphabet *alphabet=nullptr)
Key value store for additional attributes for the NFT. Keys are attribute names as strings and the value types are up to the user. For example, we can set up attributes such as "state_dict" for state dictionary attribute mapping states to their respective names, or "transition_dict" for transition dictionary adding a human-readable meaning to each transition.
Nft (const size_t num_of_states, utils::SparseSet< State > initial_states={}, utils::SparseSet< State > final_states={}, Levels levels={}, const size_t num_of_levels=DEFAULT_NUM_OF_LEVELS, Alphabet *alphabet=nullptr)
Construct a new explicit NFT with num_of_states states and optionally set initial and final states.
Nft (const Nft &other)=default
Construct a new explicit NFT from other NFT.
Nft (Nft &&other) noexcept
Nft & operator= (const Nft &other)=default
Nft & operator= (Nft &&other) noexcept
Nft (const mata::nfa::Nfa &other, const size_t num_of_levels=1, const Level default_level=DEFAULT_LEVEL)
Construct a new NFT with num_of_levels levels from NFA.
Nft (mata::nfa::Nfa &&other, const size_t num_of_levels=1, const Level default_level=DEFAULT_LEVEL)
Construct a new NFT with num_of_levels levels from NFA.
Nft & operator= (const mata::nfa::Nfa &other) noexcept
Nft & operator= (mata::nfa::Nfa &&other) noexcept
State add_state ()
Add a new (fresh) state to the automaton.
State add_state (State state)
Add state state to this if state is not in this yet.
State add_state_with_level (Level level)
Add a new (fresh) state to the automaton with level level.
State add_state_with_level (State state, Level level)
Add state state to this with level level if state is not in this yet.
size_t num_of_states_with_level (Level level) const
Get the number of states with level level.
State insert_word (State source, const Word &word, State target)
Inserts a word into the NFT from a source state source to a target state target.
State insert_word (State source, const Word &word)
Inserts a word into the NFT from a source state source to a newly created target state, creating new states along the path of the word.
State add_transition (State source, const std::vector< Symbol > &symbols, State target)
Add a single NFT transition.
State add_transition (State source, const std::vector< Symbol > &symbols)
Add a single NFT transition to the NFT from a source state source to a newly created target state, creating new inner states for all tapes.
State insert_word_by_parts (State source, const std::vector< Word > &word_parts_on_levels, State target)
Inserts a word, which is created by interleaving parts from word_parts_on_levels, into the NFT from a source state source to a target state target, creating new states along the path of word.
State insert_word_by_parts (State source, const std::vector< Word > &word_parts_on_levels)
Inserts a word, which is created by interleaving parts from word_parts_on_levels, into the NFT from a source state source to a target state target, creating new states along the path of word.
Nft & insert_identity (State state, const std::vector< Symbol > &symbols, JumpMode jump_mode=JumpMode::RepeatSymbol)
Inserts identity transitions into the NFT.
Nft & insert_identity (State state, const Alphabet *alphabet, JumpMode jump_mode=JumpMode::RepeatSymbol)
Inserts identity transitions into the NFT.
Nft & insert_identity (State state, Symbol symbol, JumpMode jump_mode=JumpMode::RepeatSymbol)
Inserts an identity transition into the NFT.
bool contains_jump_transitions () const
Checks if the transducer contains any jump transition.
void clear ()
Clear the underlying NFT to a blank NFT.
bool is_identical (const Nft &aut) const
Check if this is exactly identical to aut.
Nft & trim (StateRenaming *state_renaming=nullptr)
Remove inaccessible (unreachable) and not co-accessible (non-terminating) states in-place.
void remove_epsilon (Symbol epsilon=EPSILON)
Remove simple epsilon transitions from the automaton.
Nft & concatenate (const Nft &aut)
In-place concatenation.
Nft & unite_nondet_with (const Nft &aut)
In-place union.
Nft get_one_letter_aut (const std::set< Level > &levels_to_keep={}, Symbol abstract_symbol='x') const
Unify transitions to create a directed graph with at most a single transition between two states.
void get_one_letter_aut (Nft &result) const
Unify transitions to create a directed graph with at most a single transition between two states.
void unwind_jumps_inplace (const utils::OrdVector< Symbol > &dont_care_symbol_replacements={ DONT_CARE }, JumpMode jump_mode=JumpMode::RepeatSymbol)
Unwinds jump transitions in the transducer.
Nft unwind_jumps (const utils::OrdVector< Symbol > &dont_care_symbol_replacements={ DONT_CARE }, JumpMode jump_mode=JumpMode::RepeatSymbol) const
Creates a transducer with unwinded jump transitions from the current one.
void unwind_jumps (Nft &result, const utils::OrdVector< Symbol > &dont_care_symbol_replacements={ DONT_CARE }, JumpMode jump_mode=JumpMode::RepeatSymbol) const
Unwinds jump transitions in the given transducer.
std::string print_to_dot (bool decode_ascii_chars=false, bool use_intervals=false, int max_label_length=-1) const
Prints the automaton in DOT format.
void print_to_dot (std::ostream &output, bool decode_ascii_chars=false, bool use_intervals=false, int max_label_length=-1) const
Prints the automaton to the output stream in DOT format.
void print_to_dot (const std::string &filename, bool decode_ascii_chars=false, bool use_intervals=false, int max_label_length=-1) const
Prints the automaton to the file in DOT format.
std::string print_to_mata () const
Prints the automaton in mata format.
void print_to_mata (std::ostream &output) const
Prints the automaton to the output stream in mata format.
void print_to_mata (const std::string &filename) const
Prints the automaton to the file in mata format.
StateSet post (const StateSet &states, const Symbol symbol, EpsilonClosureOpt epsilon_closure_opt=EpsilonClosureOpt::NONE) const
Get the set of states reachable from the given set of states over the given symbol.
StateSet post (const State state, const Symbol symbol, EpsilonClosureOpt epsilon_closure_opt) const
Get the set of states reachable from the given state over the given symbol.
const StateSet & post (const State state, Symbol symbol) const
Returns a reference to targets (states) reachable from the given state over the given symbol.
bool is_universal (const Alphabet &alphabet, Run *cex=nullptr, const ParameterMap &params={{ "algorithm", "antichains" }}) const
Is the language of the automaton universal?
bool is_universal (const Alphabet &alphabet, const ParameterMap &params) const
Is the language of the automaton universal?
bool is_in_lang (const Run &word, bool use_epsilon=false, bool match_prefix=false) const
Check whether a run over the word (or its prefix) is in the language of an automaton.
bool is_in_lang (const Word &word, const bool use_epsilon=false, const bool match_prefix=false)
Check whether a word (or its prefix) is in the language of an automaton.
bool is_prefix_in_lang (const Run &word, const bool use_epsilon=false) const
Check whether a prefix of a run is in the language of an automaton.
bool is_prefix_in_lang (const Word &word, const bool use_epsilon=false) const
Check whether a prefix of a word is in the language of an automaton.
bool is_tuple_in_lang (const std::vector< Word > &track_words)
Checks whether track words are in the language of the transducer.
std::pair< Run, bool > get_word_for_path (const Run &run) const
std::set< Word > get_words (size_t max_length) const
Get the set of all words in the language of the automaton whose length is <= max_length.
Nft apply (const nfa::Nfa &nfa, Level level_to_apply_on=0, bool project_out_applied_level=true, JumpMode jump_mode=JumpMode::RepeatSymbol) const
Apply nfa to this.
Nft apply (const Word &word, Level level_to_apply_on=0, bool project_out_applied_level=true, JumpMode jump_mode=JumpMode::RepeatSymbol) const
Apply word to this.
Nfa to_nfa_copy () const
Copy NFT as NFA.
Nfa to_nfa_move ()
Move NFT as NFA.
Nfa to_nfa_update_copy (const utils::OrdVector< Symbol > &dont_care_symbol_replacements={ DONT_CARE }, JumpMode jump_mode=JumpMode::RepeatSymbol) const
Copy NFT as NFA updating the transitions to have one level only.
Nfa to_nfa_update_move (const utils::OrdVector< Symbol > &dont_care_symbol_replacements={ DONT_CARE }, JumpMode jump_mode=JumpMode::RepeatSymbol)
Move NFT as NFA updating the transitions to have one level only.
size_t num_of_states () const
Get the current number of states in the whole automaton.
Nfa & unify_initial (bool force_new_state=false)
Unify initial states into a single new initial state.
Nfa & unify_final (bool force_new_state=false)
Unify final states into a single new final state.
Nfa & swap_final_nonfinal ()
Swap final and non-final states in-place.
bool is_state (const State &state_to_check) const
bool is_identical (const Nfa &aut) const
Check if this is exactly identical to aut.
StateSet get_reachable_states () const
Get set of reachable states.
StateSet get_terminating_states () const
Get set of terminating states.
BoolVector get_useful_states () const
Get the useful states using a modified Tarjan's algorithm.
void tarjan_scc_discover (const TarjanDiscoverCallback &callback) const
Tarjan's SCC discover algorihm.
Nfa decode_utf8 () const
Decodes automaton from UTF-8 encoding.
std::vector< State > distances_from_initial () const
Returns vector ret where ret[q] is the length of the shortest path from any initial state to q.
std::vector< State > distances_to_final () const
Returns vector ret where ret[q] is the length of the shortest path from q to any final state.
Run get_shortest_accepting_run_from_state (State q, const std::vector< State > &distances_to_final) const
Get some shortest accepting run from state q.
Nfa & concatenate (const Nfa &aut)
In-place concatenation.
Nfa & unite_nondet_with (const Nfa &aut)
In-place nondeterministic union with aut.
Nfa get_one_letter_aut (Symbol abstract_symbol='x') const
Unify transitions to create a directed graph with at most a single transition between two states.
void get_one_letter_aut (Nfa &result) const
Unify transitions to create a directed graph with at most a single transition between two states.
bool is_epsilon (Symbol symbol) const
Check whether symbol is epsilon symbol or not.
std::string print_to_mata (const Alphabet *alphabet=nullptr) const
Prints the automaton in mata format.
void print_to_mata (std::ostream &output, const Alphabet *alphabet=nullptr) const
Prints the automaton to the output stream in mata format.
void print_to_mata (const std::string &filename, const Alphabet *alphabet=nullptr) const
Prints the automaton to the file in mata format.
bool is_lang_empty (Run *cex=nullptr) const
Check whether the language of NFA is empty.
bool is_lang_empty_scc () const
Check if the language is empty using Tarjan's SCC discover algorithm.
bool is_deterministic () const
Test whether an automaton is deterministic.
bool is_complete (Alphabet const *alphabet=nullptr) const
Test for automaton completeness with regard to an alphabet.
bool is_acyclic () const
Is the automaton graph acyclic? Used for checking language finiteness.
bool is_flat () const
Is the automaton flat?
void fill_alphabet (mata::OnTheFlyAlphabet &alphabet_to_fill) const
Fill alphabet_to_fill with symbols from nfa.
StateSet read_word (const Run &word, const bool use_epsilon=false) const
Read a word and return the set of states the automaton ends up in.
StateSet read_word (const Word &word, const bool use_epsilon=false) const
Read a word and return the set of states the automaton ends up in.
std::optional< State > read_word_det (const Run &word) const
Read a word and return the state the deterministic automaton ends up in.
std::optional< State > read_word_det (const Word &word) const
Read a word and return the state the deterministic automaton ends up in.
std::optional< Word > get_word (const std::optional< Symbol > first_epsilon=EPSILON) const
Get any arbitrary accepted word in the language of the automaton.
std::optional< Word > get_word_from_complement (const Alphabet *alphabet=nullptr) const
Get any arbitrary accepted word in the language of the complement of the automaton.
bool make_complete (const Alphabet *alphabet=nullptr, std::optional< State > sink_state=std::nullopt)
Make NFA complete in place.
bool make_complete (const utils::OrdVector< Symbol > &symbols, std::optional< State > sink_state=std::nullopt)
Make NFA complete in place.
Nfa & complement_deterministic (const mata::utils::OrdVector< Symbol > &symbols, std::optional< State > sink_state=std::nullopt)
Complement deterministic automaton in-place by adding a sink state and swapping final and non-final states.
Static Public Member Functions
static Nft with_levels (const size_t num_of_levels, const size_t num_of_states=0, Levels levels={}, utils::SparseSet< State > initial_states={}, utils::SparseSet< State > final_states={}, Alphabet *alphabet=nullptr)
static Nft with_levels (const size_t num_of_levels, Delta delta, Levels levels={}, utils::SparseSet< State > initial_states={}, utils::SparseSet< State > final_states={}, Alphabet *alphabet=nullptr)
Public Attributes
Levels levels {}
Vector of levels giving each state a level in range from 0 to num_of_levels - 1.
size_t num_of_levels { DEFAULT_NUM_OF_LEVELS }
Number of levels (tracks) the transducer recognizes.
Delta delta
For state q, delta[q] keeps the list of transitions ordered by symbols.
utils::SparseSet< State > initial {}
utils::SparseSet< State > final {}
Alphabet * alphabet = nullptr
The alphabet which can be shared between multiple automata. Key value store for additional attributes for the NFA. Keys are attribute names as strings and the value types are up to the user. For example, we can set up attributes such as "state_dict" for state dictionary attribute mapping states to their respective names, or "transition_dict" for transition dictionary adding a human-readable meaning to each transition.
std::unordered_map< std::string, void * > attributes {}
Detailed Description
A class representing an NFT.
Definition at line 140 of file nft.hh.
Constructor & Destructor Documentation
Nft() [1/6]
Nft (Delta delta = {}, utils::SparseSet< State > initial_states = {}, utils::SparseSet< State > final_states = {}, Levels levels = {}, const size_t num_of_levels = DEFAULT_NUM_OF_LEVELS, Alphabet * alphabet = nullptr) inline explicit
Key value store for additional attributes for the NFT. Keys are attribute names as strings and the value types are up to the user. For example, we can set up attributes such as "state_dict" for state dictionary attribute mapping states to their respective names, or "transition_dict" for transition dictionary adding a human-readable meaning to each transition.
Definition at line 163 of file nft.hh.
References Delta::Delta().
Nft() [2/6]
Nft (const size_t num_of_states, utils::SparseSet< State > initial_states = {}, utils::SparseSet< State > final_states = {}, Levels levels = {}, const size_t num_of_levels = DEFAULT_NUM_OF_LEVELS, Alphabet * alphabet = nullptr) inline explicit
Construct a new explicit NFT with num_of_states states and optionally set initial and final states.
Parameters
[in] num_of_states Number of states for which to preallocate Delta.
Definition at line 174 of file nft.hh.
Nft() [3/6]
Nft (const Nft & other) default
Construct a new explicit NFT from other NFT.
Nft() [4/6]
Nft (Nft && other) inline noexcept
Definition at line 196 of file nft.hh.
References Nft::levels.
Nft() [5/6]
Nft (const mata::nfa::Nfa & other, const size_t num_of_levels = 1, const Level default_level = DEFAULT_LEVEL) inline explicit
Construct a new NFT with num_of_levels levels from NFA.
All states levels are set to the default_level. The transition function remains the same as in the NFA.
Note: Constructor functions with more options are available in mata::nft::builder.
Parameters
other NFA to be converted to NFT.
num_of_levels Number of levels for the NFT. (default: 1)
default_level Default level for the states. (default: 0)
Definition at line 220 of file nft.hh.
References Nfa::Nfa().
Nft() [6/6]
Nft (mata::nfa::Nfa && other, const size_t num_of_levels = 1, const Level default_level = DEFAULT_LEVEL) inline explicit
Construct a new NFT with num_of_levels levels from NFA.
All states levels are set to the default_level. The transition function remains the same as in the NFA.
Note: Constructor functions with more options are available in mata::nft::builder.
Parameters
other NFA to be converted to NFT.
num_of_levels Number of levels for the NFT. (default: 1)
default_level Default level for the states. (default: 0)
Definition at line 233 of file nft.hh.
Member Function Documentation
add_state() [1/2]
State add_state ()
Add a new (fresh) state to the automaton.
Returns
The newly created state.
add_state() [2/2]
State add_state (State state)
Add state state to this if state is not in this yet.
Returns
The requested state.
add_state_with_level() [1/2]
State add_state_with_level (Level level)
Add a new (fresh) state to the automaton with level level.
Returns
The newly created state.
add_state_with_level() [2/2]
State add_state_with_level (State state, Level level)
Add state state to this with level level if state is not in this yet.
Returns
The requested state.
add_transition() [1/2]
State add_transition (State source, const std::vector< Symbol > & symbols)
Add a single NFT transition to the NFT from a source state source to a newly created target state, creating new inner states for all tapes.
If the length of symbols is less than num_of_levels, the last symbol of symbols will form a transition going directly from the last inner state to the newly created target.
Parameters
source The source state where the transition begins. source must already exist.
symbols The nonempty set of symbols, one for each tape to be inserted into the NFT.
Returns
The target state target.
add_transition() [2/2]
State add_transition (State source, const std::vector< Symbol > & symbols, State target)
Add a single NFT transition.
The transition leads from a source state source to a target state target, creating new inner states for all tapes.
If the length of symbols is less than num_of_levels, then the last symbol of symbols will form a jump transition going directly from the last inner state to target.
Parameters
source The source state where the NFT transition begins. source must already exist.
symbols The nonempty set of symbols, one for each tape to be inserted into the NFT.
target The target state where the NFT transition ends. target must already exist.
Returns
The target state target.
apply() [1/2]
Nft apply (const nfa::Nfa & nfa, Level level_to_apply_on = 0, bool project_out_applied_level = true, JumpMode jump_mode = JumpMode::RepeatSymbol) const
Apply nfa to this.
Intersects nfa with level level_to_apply_on of this. For 2-level NFT, the default values returns the image of nfa, where you can use to_nfa_copy() or to_nfa_move() to get NFA representation of this language. If you need pre-image of nfa for 2-level NFT, set level_to_apply_on to 1.
Parameters
nfa NFA to apply.
level_to_apply_on Which level to apply the nfa on.
project_out_applied_level Whether the level_to_apply_on is projected out from final NFT.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol, or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
apply() [2/2]
Nft apply (const Word & word, Level level_to_apply_on = 0, bool project_out_applied_level = true, JumpMode jump_mode = JumpMode::RepeatSymbol) const
Apply word to this.
Intersects { word } with level level_to_apply_on of this. For 2-level NFT, the default values returns the image of word, where you can use to_nfa_copy() or to_nfa_move() to get NFA representation of this language. If you need pre-image of word for 2-level NFT, set level_to_apply_on to 1.
Parameters
word Word to apply.
level_to_apply_on Which level to apply the nfa on.
project_out_applied_level Whether the level_to_apply_on is projected out from final NFT.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol, or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
clear()
void clear ()
Clear the underlying NFT to a blank NFT.
The whole NFT is cleared, each member is set to its zero value.
complement_deterministic()
Nfa & complement_deterministic (const mata::utils::OrdVector< Symbol > & symbols, std::optional< State > sink_state = std::nullopt) inherited
Complement deterministic automaton in-place by adding a sink state and swapping final and non-final states.
Parameters
[in] symbols Symbols needed to make the automaton complete.
[in] sink_state State to be used as a sink state. Adds a new sink state when not specified.
Returns
DFA complemented in-place.
Precondition
this is a deterministic automaton.
concatenate() [1/2]
Nfa & concatenate (const Nfa & aut) inherited
In-place concatenation.
concatenate() [2/2]
Nft & concatenate (const Nft & aut)
In-place concatenation.
contains_jump_transitions()
bool contains_jump_transitions () const
Checks if the transducer contains any jump transition.
decode_utf8()
Nfa decode_utf8 () const inherited
Decodes automaton from UTF-8 encoding.
Method removes unreachable states from delta.
Returns
Decoded automaton.
distances_from_initial()
std::vector< State > distances_from_initial () const inherited
Returns vector ret where ret[q] is the length of the shortest path from any initial state to q.
distances_to_final()
std::vector< State > distances_to_final () const inherited
Returns vector ret where ret[q] is the length of the shortest path from q to any final state.
fill_alphabet()
void fill_alphabet (mata::OnTheFlyAlphabet & alphabet_to_fill) const inherited
Fill alphabet_to_fill with symbols from nfa.
Parameters
[in] nfa NFA with symbols to fill alphabet_to_fill with.
[out] alphabet_to_fill Alphabet to be filled with symbols from nfa.
Referenced by mata::nfa::create_alphabet().
get_one_letter_aut() [1/4]
Nft get_one_letter_aut (const std::set< Level > & levels_to_keep = {}, Symbol abstract_symbol = 'x') const
Unify transitions to create a directed graph with at most a single transition between two states.
Parameters
[in] abstract_symbol Abstract symbol to use for transitions in digraph.
Returns
An automaton representing a directed graph.
Get NFT where transitions of this are replaced with transitions over one symbol abstract_symbol
The transitions over EPSILON are not replaced, neither are the transitions coming from a state with a level from levels_to_keep.
Parameters
[in] levels_to_keep Transitions coming from states with any of these levels are not replaced.
[in] abstract_symbol The symbol to replace with.
Returns
Nft
get_one_letter_aut() [2/4]
void get_one_letter_aut (Nfa & result) const inherited
Unify transitions to create a directed graph with at most a single transition between two states.
Parameters
[out] result An automaton representing a directed graph.
get_one_letter_aut() [3/4]
void get_one_letter_aut (Nft & result) const
Unify transitions to create a directed graph with at most a single transition between two states.
Parameters
[out] result An automaton representing a directed graph.
get_one_letter_aut() [4/4]
Nfa get_one_letter_aut (Symbol abstract_symbol = 'x') const inherited
Unify transitions to create a directed graph with at most a single transition between two states.
Parameters
[in] abstract_symbol Abstract symbol to use for transitions in digraph.
Returns
An automaton representing a directed graph.
get_reachable_states()
StateSet get_reachable_states () const inherited
Get set of reachable states.
Reachable states are states accessible from any initial state.
Returns
Set of reachable states. TODO: with the new get_useful_states, it might be useless now.
get_shortest_accepting_run_from_state()
Run get_shortest_accepting_run_from_state (State q, const std::vector< State > & distances_to_final) const inherited
Get some shortest accepting run from state q.
Assumes that q is a state of this automaton and that there is some accepting run from q
Parameters
distances_to_final Vector of the lengths of the shortest runs from states (can be computed using distances_to_final())
get_terminating_states()
StateSet get_terminating_states () const inherited
Get set of terminating states.
Terminating states are states leading to any final state.
Returns
Set of terminating states. TODO: with the new get_useful_states, it might be useless now.
get_useful_states()
BoolVector get_useful_states () const inherited
Get the useful states using a modified Tarjan's algorithm.
A state is useful if it is reachable from an initial state and can reach a final state.
Returns
BoolVector Bool vector whose ith value is true iff the state i is useful.
get_word()
std::optional< Word > get_word (const std::optional< Symbol > first_epsilon = EPSILON) const inherited
Get any arbitrary accepted word in the language of the automaton.
The automaton is searched using DFS, returning a word for the first reached final state.
Parameters
first_epsilon If defined, all symbols >=first_epsilon are assumed to be epsilon and therefore are not in the returned word.
Returns
std::optional<Word> Some word from the language. If the language is empty, returns std::nullopt.
get_word_for_path()
std::pair< Run, bool > get_word_for_path (const Run & run) const
get_word_from_complement()
std::optional< Word > get_word_from_complement (const Alphabet * alphabet = nullptr) const inherited
Get any arbitrary accepted word in the language of the complement of the automaton.
The automaton is lazily determinized and made complete. The algorithm returns an arbitrary word from the complemented NFA constructed until the first macrostate without any final states in the original automaton is encountered.
Parameters
[in] alphabet Alphabet to use for computing the complement. If nullptr, uses this->alphabet when defined, otherwise uses this->delta.get_used_symbols().
Precondition
The automaton does not contain any epsilon transitions. TODO: Support lazy epsilon closure?
Returns
An arbitrary word from the complemented automaton, or std::nullopt if the automaton is universal on the chosen set of symbols for the complement.
get_words()
std::set< Word > get_words (size_t max_length) const
Get the set of all words in the language of the automaton whose length is <= max_length.
If you have an automaton with finite language (can be checked using is_acyclic), you can get all words by calling get_words(aut.num_of_states())
insert_identity() [1/3]
Nft & insert_identity (State state, const Alphabet * alphabet, JumpMode jump_mode = JumpMode::RepeatSymbol)
Inserts identity transitions into the NFT.
Parameters
state The state where the identity transition will be inserted. state server as both the source and target state.
alpahbet The alphabet with symbols used for the identity transition. Identity will be created for each symbol in the alphabet.
jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
Self with inserted identity.
insert_identity() [2/3]
Nft & insert_identity (State state, const std::vector< Symbol > & symbols, JumpMode jump_mode = JumpMode::RepeatSymbol)
Inserts identity transitions into the NFT.
Parameters
state The state where the identity transition will be inserted. state server as both the source and target state.
symbols The vector of symbols used for the identity transition. Identity will be created for each symbol in the vector.
jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
Self with inserted identity.
insert_identity() [3/3]
Nft & insert_identity (State state, Symbol symbol, JumpMode jump_mode = JumpMode::RepeatSymbol)
Inserts an identity transition into the NFT.
Parameters
state The state where the identity transition will be inserted. state server as both the source and target state.
symbol The symbol used for the identity transition.
jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
Self with inserted identity.
insert_word() [1/2]
State insert_word (State source, const Word & word)
Inserts a word into the NFT from a source state source to a newly created target state, creating new states along the path of the word.
If the length of word is less than num_of_levels, then the last symbol of word will form a transition going directly from the last inner state to the newly created target.
Parameters
source The source state where the word begins. source must already exist.
word The nonempty word to be inserted into the NFA.
Returns
The newly created target where the inserted word ends.
insert_word() [2/2]
State insert_word (State source, const Word & word, State target)
Inserts a word into the NFT from a source state source to a target state target.
Creates new states along the path of the word.
If the length of word is less than num_of_levels, then the last symbol of word will form a transition going directly from the last inner state to target.
Parameters
source The source state where the word begins. source must already exist.
word The nonempty word to be inserted into the NFA.
target The target state where the word ends. target must already exist.
Returns
The state target where the inserted word ends.
insert_word_by_parts() [1/2]
State insert_word_by_parts (State source, const std::vector< Word > & word_parts_on_levels)
Inserts a word, which is created by interleaving parts from word_parts_on_levels, into the NFT from a source state source to a target state target, creating new states along the path of word.
The length of the inserted word equals num_of_levels * the maximum word length in the vector word_parts_on_levels. At least one Word in word_parts_on_levels must be nonempty. The vector word_parts_on_levels must have a size equal to num_of_levels. Words shorter than the maximum word length are interpreted as words followed by a sequence of epsilons to match the maximum length.
Parameters
source The source state where the word begins. source must already exist be of a level 0.
word_parts_on_levels The vector of word parts, with each part corresponding to a different level.
Returns
The newly created target where the inserted word_parts_on_levels ends.
insert_word_by_parts() [2/2]
State insert_word_by_parts (State source, const std::vector< Word > & word_parts_on_levels, State target)
Inserts a word, which is created by interleaving parts from word_parts_on_levels, into the NFT from a source state source to a target state target, creating new states along the path of word.
The length of the inserted word equals num_of_levels * the maximum word length in the vector word_parts_on_levels. At least one Word in word_parts_on_levels must be nonempty. The vector word_parts_on_levels must have a size equal to num_of_levels. Words shorter than the maximum word length are interpreted as words followed by a sequence of epsilons to match the maximum length.
Parameters
source The source state where the word begins. source must already exist and be of a level 0.
word_parts_on_levels The vector of word parts, with each part corresponding to a different level.
target The target state where the word ends. target must already exist and be of a level 0.
Returns
The state target where the inserted word_parts_on_levels ends.
is_acyclic()
bool is_acyclic () const inherited
Is the automaton graph acyclic? Used for checking language finiteness.
Returns
true <-> Automaton graph is acyclic.
is_complete()
bool is_complete (Alphabet const * alphabet = nullptr) const inherited
Test for automaton completeness with regard to an alphabet.
An automaton is complete if every reachable state has at least one outgoing transition over every symbol.
is_deterministic()
bool is_deterministic () const inherited
Test whether an automaton is deterministic.
I.e., whether it has exactly one initial state and every state has at most one outgoing transition over every symbol. Checks the whole automaton, not only the reachable part
is_epsilon()
bool is_epsilon (Symbol symbol) const inline inherited
Check whether symbol is epsilon symbol or not.
Parameters
symbol Symbol to check.
Returns
True if the passed symbol is epsilon, false otherwise.
Definition at line 291 of file nfa.hh.
References mata::nfa::EPSILON.
is_flat()
bool is_flat () const inherited
Is the automaton flat?
Flat automaton is an NFA whose every SCC is a simple loop. Basically each state in an SCC has at most one successor within this SCC.
Returns
true <-> Automaton graph is flat.
is_identical() [1/2]
bool is_identical (const Nfa & aut) const inherited
Check if this is exactly identical to aut.
This is exact equality of automata, including state numbering (so even stronger than isomorphism), essentially only useful for testing purposes.
Returns
True if automata are exactly identical, false otherwise.
is_identical() [2/2]
bool is_identical (const Nft & aut) const
Check if this is exactly identical to aut.
This is exact equality of automata, including state numbering (so even stronger than isomorphism), essentially only useful for testing purposes.
Returns
True if automata are exactly identical, false otherwise.
is_in_lang() [1/2]
bool is_in_lang (const Run & word, bool use_epsilon = false, bool match_prefix = false) const
Check whether a run over the word (or its prefix) is in the language of an automaton.
Parameters
word The run to check.
use_epsilon Whether the automaton uses epsilon transitions.
match_prefix Whether to also match the prefix of the word.
Returns
True if the run (or its prefix) is in the language of the automaton, false otherwise.
Referenced by Nft::is_in_lang(), and Nft::is_prefix_in_lang().
is_in_lang() [2/2]
bool is_in_lang (const Word & word, const bool use_epsilon = false, const bool match_prefix = false) inline
Check whether a word (or its prefix) is in the language of an automaton.
Parameters
word The word to check.
use_epsilon Whether the automaton uses epsilon transitions.
match_prefix Whether to also match the prefix of the word.
Returns
True if the word (or its prefix) is in the language of the automaton, false otherwise.
Definition at line 623 of file nft.hh.
References Nft::is_in_lang().
is_lang_empty()
bool is_lang_empty (Run * cex = nullptr) const inherited
Check whether the language of NFA is empty.
Currently calls is_lang_empty_scc if cex is null
Parameters
[out] cex Counter-example path for a case the language is not empty.
Returns
True if the language is empty, false otherwise.
is_lang_empty_scc()
bool is_lang_empty_scc () const inherited
Check if the language is empty using Tarjan's SCC discover algorithm.
Returns
Language empty <-> True
is_prefix_in_lang() [1/2]
bool is_prefix_in_lang (const Run & word, const bool use_epsilon = false) const inline
Check whether a prefix of a run is in the language of an automaton.
Parameters
word The run to check.
use_epsilon Whether the automaton uses epsilon transitions.
Returns
True if the prefix of the run is in the language of the automaton, false otherwise.
Definition at line 635 of file nft.hh.
References Nft::is_in_lang().
Referenced by Nft::is_prefix_in_lang().
is_prefix_in_lang() [2/2]
bool is_prefix_in_lang (const Word & word, const bool use_epsilon = false) const inline
Check whether a prefix of a word is in the language of an automaton.
Parameters
word The word to check.
use_epsilon Whether the automaton uses epsilon transitions.
Returns
True if the prefix of the word is in the language of the automaton, false otherwise.
Definition at line 645 of file nft.hh.
References Nft::is_prefix_in_lang().
is_state()
bool is_state (const State & state_to_check) const inline inherited
Definition at line 157 of file nfa.hh.
is_tuple_in_lang()
bool is_tuple_in_lang (const std::vector< Word > & track_words)
Checks whether track words are in the language of the transducer.
That is, the function checks whether a tuple track_words (word1, word2, word3, ..., wordn) is in the regular relation accepted by the transducer with 'n' levels (tracks).
is_universal() [1/2]
bool is_universal (const Alphabet & alphabet, const ParameterMap & params) const
Is the language of the automaton universal?
is_universal() [2/2]
bool is_universal (const Alphabet & alphabet, Run * cex = nullptr, const ParameterMap & params = {{ "algorithm", "antichains" }}) const
Is the language of the automaton universal?
make_complete() [1/2]
bool make_complete (const Alphabet * alphabet = nullptr, std::optional< State > sink_state = std::nullopt) inherited
Make NFA complete in place.
For each state 0,...,this->num_of_states()-1, add transitions with "missing" symbols from alphabet (symbols that do not occur on transitions from given state) to sink_state. If sink_state does not belong to the NFA, it is added to it, but only in the case that some transition to sink_state was added. In the case that NFA does not contain any states, this function does nothing.
Parameters
[in] alphabet Alphabet to use for computing "missing" symbols. If nullptr, use this->alphabet when defined, otherwise use this->delta.get_used_symbols().
[in] sink_state The state into which new transitions are added. If std::nullopt, add a new sink state.
Returns
true if a new transition was added to the NFA.
make_complete() [2/2]
bool make_complete (const utils::OrdVector< Symbol > & symbols, std::optional< State > sink_state = std::nullopt) inherited
Make NFA complete in place.
For each state 0,...,this->num_of_states()-1, add transitions with "missing" symbols from alphabet (symbols that do not occur on transitions from given state) to sink_state. If sink_state does not belong to the NFA, it is added to it, but only in the case that some transition to sink_state was added. In the case that NFA does not contain any states, this function does nothing.
This overloaded version is a more efficient version which does not need to compute the set of symbols to complete to from the alphabet. Prefer this version when you already have the set of symbols precomputed or plan to complete multiple automata over the same set of symbols.
Parameters
[in] symbols Symbols to compute "missing" symbols from.
[in] sink_state The state into which new transitions are added. If std::nullopt, add a new sink state.
Returns
true if a new transition was added to the NFA.
num_of_states()
size_t num_of_states () const inherited
Get the current number of states in the whole automaton.
This includes the initial and final states as well as states in the transition relation.
Returns
The number of states.
num_of_states_with_level()
size_t num_of_states_with_level (Level level) const
Get the number of states with level level.
Returns
The number of states with level level.
operator=() [1/4]
Nft & operator= (const mata::nfa::Nfa & other) noexcept
operator=() [2/4]
Nft & operator= (const Nft & other) default
operator=() [3/4]
Nft & operator= (mata::nfa::Nfa && other) noexcept
operator=() [4/4]
Nft & operator= (Nft && other) noexcept
Referenced by mata::nft::plumbing::minimize(), mata::nft::plumbing::remove_epsilon(), mata::nft::plumbing::revert(), and mata::nft::plumbing::union_nondet().
post() [1/3]
StateSet post (const State state, const Symbol symbol, EpsilonClosureOpt epsilon_closure_opt) const inline
Get the set of states reachable from the given state over the given symbol.
Parameters
state A state to compute the post set from.
symbol Symbol to compute the post set for.
epsilon_closure_opt Epsilon closure option. Perform epsilon closure before and/or after the post operation.
Returns
Set of states reachable from the given state over the given symbol.
Definition at line 579 of file nft.hh.
References Nft::post().
post() [2/3]
const StateSet & post (const State state, Symbol symbol) const inline
Returns a reference to targets (states) reachable from the given state over the given symbol.
This is an optimized shortcut for post(state, symbol, EpsilonClosureOpt::NONE).
Parameters
state A state to compute the post set from.
symbol Symbol to compute the post set for.
Returns
Set of states reachable from the given state over the given symbol.
Definition at line 592 of file nft.hh.
post() [3/3]
StateSet post (const StateSet & states, const Symbol symbol, EpsilonClosureOpt epsilon_closure_opt = EpsilonClosureOpt::NONE) const
Get the set of states reachable from the given set of states over the given symbol.
TODO: Relict from VATA. What to do with inclusion/ universality/ this post function? Revise all of them.
Parameters
states Set of states to compute the post set from.
symbol Symbol to compute the post set for.
epsilon_closure_opt Epsilon closure option. Perform epsilon closure before and/or after the post operation.
Returns
Set of states reachable from the given set of states over the given symbol.
Referenced by Nft::post().
print_to_dot() [1/3]
std::string print_to_dot (bool decode_ascii_chars = false, bool use_intervals = false, int max_label_length = -1) const
Prints the automaton in DOT format.
Parameters
[in] decode_ascii_chars Whether to use ASCII characters for the output.
[in] use_intervals Whether to use intervals (e.g. [1-3] instead of 1,2,3) for labels.
[in] max_label_length Maximum label length for the output (-1 means no limit, 0 means no labels). If the label is longer than max_label_length, it will be truncated, with full label displayed on hover.
Returns
automaton in DOT format
print_to_dot() [2/3]
void print_to_dot (const std::string & filename, bool decode_ascii_chars = false, bool use_intervals = false, int max_label_length = -1) const
Prints the automaton to the file in DOT format.
Parameters
filename Name of the file to print the automaton to
[in] decode_ascii_chars Whether to use ASCII characters for the output.
[in] use_intervals Whether to use intervals (e.g. [1-3] instead of 1,2,3) for labels.
[in] max_label_length Maximum label length for the output (-1 means no limit, 0 means no labels). If the label is longer than max_label_length, it will be truncated, with full label displayed on hover.
print_to_dot() [3/3]
void print_to_dot (std::ostream & output, bool decode_ascii_chars = false, bool use_intervals = false, int max_label_length = -1) const
Prints the automaton to the output stream in DOT format.
Parameters
[in] decode_ascii_chars Whether to use ASCII characters for the output.
[in] use_intervals Whether to use intervals (e.g. [1-3] instead of 1,2,3) for labels.
[in] max_label_length Maximum label length for the output (-1 means no limit, 0 means no labels). If the label is longer than max_label_length, it will be truncated, with full label displayed on hover.
print_to_mata() [1/6]
std::string print_to_mata () const
Prints the automaton in mata format.
If you need to parse the automaton again, use IntAlphabet in construct()
Returns
automaton in mata format TODO handle alphabet of the automaton, currently we print the exact value of the symbols
print_to_mata() [2/6]
std::string print_to_mata (const Alphabet * alphabet = nullptr) const inherited
Prints the automaton in mata format.
If you need to parse the automaton again, use IntAlphabet in construct()
Parameters
[in] alphabet If specified, translates the symbols to their symbol names in the alphabet.
Returns
automaton in mata format
print_to_mata() [3/6]
void print_to_mata (const std::string & filename) const
Prints the automaton to the file in mata format.
Parameters
filename Name of the file to print the automaton to
If you need to parse the automaton again, use IntAlphabet in construct()
TODO handle alphabet of the automaton, currently we print the exact value of the symbols
print_to_mata() [4/6]
void print_to_mata (const std::string & filename, const Alphabet * alphabet = nullptr) const inherited
Prints the automaton to the file in mata format.
If you need to parse the automaton again, use IntAlphabet in construct()
Parameters
[in] alphabet If specified, translates the symbols to their symbol names in the alphabet.
filename Name of the file to print the automaton to
print_to_mata() [5/6]
void print_to_mata (std::ostream & output) const
Prints the automaton to the output stream in mata format.
If you need to parse the automaton again, use IntAlphabet in construct()
TODO handle alphabet of the automaton, currently we print the exact value of the symbols
print_to_mata() [6/6]
void print_to_mata (std::ostream & output, const Alphabet * alphabet = nullptr) const inherited
Prints the automaton to the output stream in mata format.
If you need to parse the automaton again, use IntAlphabet in construct()
Parameters
[in] alphabet If specified, translates the symbols to their symbol names in the alphabet.
read_word() [1/2]
StateSet read_word (const Run & word, const bool use_epsilon = false) const inherited
Read a word and return the set of states the automaton ends up in.
Parameters
word The word to read.
use_epsilon Whether the automaton uses epsilon transitions.
Returns
Set of all reachable states after reading the word. Note: This returns all reachable states, not just final states. Use is_in_lang() if you need to check language membership, or intersect the result with final states manually if needed. Note: The returned set is empty if the word cannot be read.
Referenced by Nfa::read_word().
read_word() [2/2]
StateSet read_word (const Word & word, const bool use_epsilon = false) const inline inherited
Read a word and return the set of states the automaton ends up in.
Parameters
word The word to read.
use_epsilon Whether the automaton uses epsilon transitions.
Returns
Set of all reachable states after reading the word. Note: This returns all reachable states, not just final states. Use is_in_lang() if you need to check language membership, or intersect the result with final states manually if needed. Note: The returned set is empty if the word cannot be read.
Definition at line 529 of file nfa.hh.
References Nfa::read_word().
read_word_det() [1/2]
std::optional< State > read_word_det (const Run & word) const inherited
Read a word and return the state the deterministic automaton ends up in.
If the automaton is nondeterministic, the result is undefined.
Parameters
word The word to read.
Returns
The reachable state after reading the word or std::nullopt if the word cannot be read.
Referenced by Nfa::read_word_det().
read_word_det() [2/2]
std::optional< State > read_word_det (const Word & word) const inline inherited
Read a word and return the state the deterministic automaton ends up in.
If the automaton is nondeterministic, the result is undefined.
Parameters
word The word to read.
Returns
The reachable state after reading the word or std::nullopt if the word cannot be read.
Definition at line 551 of file nfa.hh.
References Nfa::read_word_det().
remove_epsilon()
void remove_epsilon (Symbol epsilon = EPSILON)
Remove simple epsilon transitions from the automaton.
See also
mata::nft::remove_epsilon()
swap_final_nonfinal()
Nfa & swap_final_nonfinal () inline inherited
Swap final and non-final states in-place.
Definition at line 155 of file nfa.hh.
tarjan_scc_discover()
void tarjan_scc_discover (const TarjanDiscoverCallback & callback) const inherited
Tarjan's SCC discover algorihm.
Parameters
callback Callbacks class to instantiate callbacks for the Tarjan's algorithm.
to_nfa_copy()
Nfa to_nfa_copy () const inline
Copy NFT as NFA.
Transitions are not updated to only have one level.
Returns
A newly created NFA with copied members from NFT.
Definition at line 708 of file nft.hh.
to_nfa_move()
Nfa to_nfa_move () inline
Move NFT as NFA.
The NFT can no longer be used. Transitions are not updated to only have one level.
Returns
A newly created NFA with moved members from NFT.
Definition at line 717 of file nft.hh.
to_nfa_update_copy()
Nfa to_nfa_update_copy (const utils::OrdVector< Symbol > & dont_care_symbol_replacements = { DONT_CARE }, JumpMode jump_mode = JumpMode::RepeatSymbol) const
Copy NFT as NFA updating the transitions to have one level only.
Parameters
[in] dont_care_symbol_replacements Vector of symbols to replace DONT_CARE symbols with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A newly created NFA with copied members from NFT with updated transitions.
References mata::nft::DONT_CARE.
to_nfa_update_move()
Nfa to_nfa_update_move (const utils::OrdVector< Symbol > & dont_care_symbol_replacements = { DONT_CARE }, JumpMode jump_mode = JumpMode::RepeatSymbol)
Move NFT as NFA updating the transitions to have one level only.
The NFT can no longer be used.
Parameters
[in] dont_care_symbol_replacements Vector of symbols to replace DONT_CARE symbols with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A newly created NFA with moved members from NFT with updated transitions.
References mata::nft::DONT_CARE.
trim()
Nft & trim (StateRenaming * state_renaming = nullptr)
Remove inaccessible (unreachable) and not co-accessible (non-terminating) states in-place.
Remove states which are not accessible (unreachable; state is accessible when the state is the endpoint of a path starting from an initial state) or not co-accessible (non-terminating; state is co-accessible when the state is the starting point of a path ending in a final state).
Parameters
[out] state_renaming Mapping of trimmed states to new states.
Returns
this after trimming.
unify_final()
Nfa & unify_final (bool force_new_state = false) inherited
Unify final states into a single new final state.
Parameters
[in] force_new_state Whether to force creating a new state even when final states are already unified.
Returns
this after unification.
unify_initial()
Nfa & unify_initial (bool force_new_state = false) inherited
Unify initial states into a single new initial state.
Parameters
[in] force_new_state Whether to force creating a new state even when initial states are already unified.
Returns
this after unification.
unite_nondet_with() [1/2]
Nfa & unite_nondet_with (const Nfa & aut) inherited
In-place nondeterministic union with aut.
Does not add epsilon transitions, just unites initial and final states.
unite_nondet_with() [2/2]
Nft & unite_nondet_with (const Nft & aut)
In-place union.
unwind_jumps() [1/2]
Nft unwind_jumps (const utils::OrdVector< Symbol > & dont_care_symbol_replacements = { DONT_CARE }, JumpMode jump_mode = JumpMode::RepeatSymbol) const
Creates a transducer with unwinded jump transitions from the current one.
Parameters
[in] dont_care_symbol_replacements Vector of symbols to replace DONT_CARE symbols with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
References mata::nft::DONT_CARE.
unwind_jumps() [2/2]
void unwind_jumps (Nft & result, const utils::OrdVector< Symbol > & dont_care_symbol_replacements = { DONT_CARE }, JumpMode jump_mode = JumpMode::RepeatSymbol) const
Unwinds jump transitions in the given transducer.
Parameters
[out] result A transducer with only one level.
[in] dont_care_symbol_replacements Vector of symbols to replace DONT_CARE symbols with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
References mata::nft::DONT_CARE.
unwind_jumps_inplace()
void unwind_jumps_inplace (const utils::OrdVector< Symbol > & dont_care_symbol_replacements = { DONT_CARE }, JumpMode jump_mode = JumpMode::RepeatSymbol)
Unwinds jump transitions in the transducer.
Parameters
[in] dont_care_symbol_replacements Vector of symbols to replace DONT_CARE symbols with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
References mata::nft::DONT_CARE.
with_levels() [1/2]
static Nft with_levels (const size_t num_of_levels, const size_t num_of_states = 0, Levels levels = {}, utils::SparseSet< State > initial_states = {}, utils::SparseSet< State > final_states = {}, Alphabet * alphabet = nullptr) inline static
Definition at line 182 of file nft.hh.
with_levels() [2/2]
static Nft with_levels (const size_t num_of_levels, Delta delta, Levels levels = {}, utils::SparseSet< State > initial_states = {}, utils::SparseSet< State > final_states = {}, Alphabet * alphabet = nullptr) inline static
Definition at line 186 of file nft.hh.
Member Data Documentation
alphabet
Alphabet* alphabet = nullptr inherited
The alphabet which can be shared between multiple automata. Key value store for additional attributes for the NFA. Keys are attribute names as strings and the value types are up to the user. For example, we can set up attributes such as "state_dict" for state dictionary attribute mapping states to their respective names, or "transition_dict" for transition dictionary adding a human-readable meaning to each transition.
Definition at line 59 of file nfa.hh.
attributes
std::unordered_map<std::string, void*> attributes {} inherited
Definition at line 67 of file nfa.hh.
delta
Delta delta inherited
For state q, delta[q] keeps the list of transitions ordered by symbols.
The set of states of this automaton are the numbers from 0 to the number of states minus one.
Definition at line 55 of file nfa.hh.
final
utils::SparseSet<State> final {} inherited
Definition at line 57 of file nfa.hh.
initial
utils::SparseSet<State> initial {} inherited
Definition at line 56 of file nfa.hh.
levels
Levels levels {}
Vector of levels giving each state a level in range from 0 to num_of_levels - 1.
For state q, levels[q] gives the state q a level.
Definition at line 147 of file nft.hh.
Referenced by Nft::Nft().
num_of_levels
size_t num_of_levels { DEFAULT_NUM_OF_LEVELS }
Number of levels (tracks) the transducer recognizes.
Each transducer transition will comprise num_of_levels of NFA transitions.
Definition at line 152 of file nft.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/nft/nft.hh