Mata: Alphabet Class Reference
Alphabet Class Reference abstract
The abstract interface for NFA alphabets.
#include <alphabet.hh>
Public Member Functions
virtual Symbol translate_symb (const std::string &symb)=0
translates a string into a symbol
virtual Word translate_word (const WordName &word_name) const
Translate sequence of symbol names to sequence of their respective values.
virtual std::string reverse_translate_symbol (Symbol symbol) const =0
Translate internal symbol representation back to its original string name.
Symbol operator[] (const std::string &symb)
also translates strings to symbols
virtual utils::OrdVector< Symbol > get_alphabet_symbols () const
Get a set of all symbols in the alphabet.
virtual utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > &symbols) const
complement of a set of symbols wrt the alphabet
virtual ~Alphabet ()=default
virtual bool is_equal (const Alphabet &other_alphabet) const
Check whether two alphabets are equal.
virtual bool is_equal (const Alphabet *const other_alphabet) const
Check whether two alphabets are equal.
bool operator== (const Alphabet &) const =delete
virtual bool empty () const =0
Checks whether the alphabet has any symbols.
virtual void clear ()
Protected Member Functions
virtual const void * address () const
Detailed Description
The abstract interface for NFA alphabets.
Definition at line 23 of file alphabet.hh.
Constructor & Destructor Documentation
~Alphabet()
virtual ~Alphabet () virtual default
Member Function Documentation
address()
virtual const void * address () const inline protected virtual
Reimplemented in IntAlphabet.
Definition at line 93 of file alphabet.hh.
Referenced by Alphabet::is_equal(), and Alphabet::is_equal().
clear()
virtual void clear () inline virtual
Reimplemented in IntAlphabet, EnumAlphabet, and OnTheFlyAlphabet.
Definition at line 90 of file alphabet.hh.
empty()
virtual bool empty () const pure virtual
Checks whether the alphabet has any symbols.
Implemented in IntAlphabet, EnumAlphabet, and OnTheFlyAlphabet.
get_alphabet_symbols()
virtual utils::OrdVector< Symbol > get_alphabet_symbols () const inline virtual
Get a set of all symbols in the alphabet.
The result does not have to equal the list of symbols in the automaton using this alphabet.
Reimplemented in IntAlphabet, EnumAlphabet, and OnTheFlyAlphabet.
Definition at line 53 of file alphabet.hh.
get_complement()
virtual utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > & symbols) const inline virtual
complement of a set of symbols wrt the alphabet
Reimplemented in IntAlphabet, EnumAlphabet, and OnTheFlyAlphabet.
Definition at line 56 of file alphabet.hh.
is_equal() [1/2]
virtual bool is_equal (const Alphabet & other_alphabet) const inline virtual
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 70 of file alphabet.hh.
References Alphabet::address().
is_equal() [2/2]
virtual bool is_equal (const Alphabet *const other_alphabet) const inline virtual
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 79 of file alphabet.hh.
References Alphabet::address().
operator==()
bool operator== (const Alphabet &) const delete
operator[]()
Symbol operator[] (const std::string & symb) inline
also translates strings to symbols
Definition at line 46 of file alphabet.hh.
References Alphabet::translate_symb().
reverse_translate_symbol()
virtual std::string reverse_translate_symbol (Symbol symbol) const pure virtual
Translate internal symbol representation back to its original string name.
Throws an exception when the symbol is missing in the alphabet.
Parameters
[in] symbol Symbol to translate.
Returns
symbol original name.
Implemented in IntAlphabet, EnumAlphabet, and OnTheFlyAlphabet.
translate_symb()
virtual Symbol translate_symb (const std::string & symb) pure virtual
translates a string into a symbol
Implemented in EnumAlphabet, OnTheFlyAlphabet, and IntAlphabet.
Referenced by Alphabet::operator[]().
translate_word()
virtual Word translate_word (const WordName & word_name) const inline virtual
Translate sequence of symbol names to sequence of their respective values.
Reimplemented in EnumAlphabet, and OnTheFlyAlphabet.
Definition at line 31 of file alphabet.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/alphabet.hh