Mata: OrdVector< Key > Class Template Reference
OrdVector< Key > Class Template Reference
Implementation of a set using ordered vector.
#include <ord-vector.hh>
Public Types
using VectorType = std::vector< Key >
using value_type = Key
using size_type = size_t
using iterator = typename VectorType::iterator
using const_iterator = typename VectorType::const_iterator
using const_reference = typename VectorType::const_reference
using reference = typename VectorType::reference
Public Member Functions
OrdVector ()
OrdVector (const VectorType &vec)
OrdVector (const std::set< Key > &set)
template<class T >
OrdVector (const T &set)
OrdVector (std::initializer_list< Key > list)
OrdVector (const OrdVector &rhs)=default
OrdVector (OrdVector &&other) noexcept
OrdVector (const Key &key)
template<class InputIterator >
OrdVector (InputIterator first, InputIterator last)
OrdVector & operator= (const OrdVector &other)
OrdVector & operator= (OrdVector &&other) noexcept
virtual ~OrdVector ()=default
void insert (iterator itr, const Key &x)
template<typename... Args>
reference emplace_back (Args &&... args)
reference push_back (const Key &t)
reference push_back (Key &&t)
virtual void reserve (size_t size)
virtual void resize (size_t size)
virtual iterator erase (const_iterator pos)
virtual iterator erase (const_iterator first, const_iterator last)
virtual void insert (const Key &x)
virtual void insert (const OrdVector &vec)
void clear ()
virtual size_t size () const
size_t count (const Key &key) const
OrdVector difference (const OrdVector &rhs) const
Compute set difference as this minus rhs.
OrdVector intersection (const OrdVector &rhs) const
virtual const_iterator find (const Key &key) const
virtual iterator find (const Key &key)
virtual const Key & front () const
virtual Key & front ()
virtual const Key & min () const
virtual Key & min ()
virtual const Key & max () const
virtual Key & max ()
virtual const Key & at (const size_t index) const
virtual Key & at (const size_t index)
bool contains (const Key &key) const
Check whether key exists in the ordered vector.
size_t erase (const Key &k)
Remove k from sorted vector.
virtual bool empty () const
template<typename Fun >
void filter_indexes (const Fun &&is_staying)
template<typename Fun >
void filter (const Fun &&is_staying)
virtual const_reference back () const
virtual reference back ()
Get reference to the last element in the vector.
virtual void pop_back ()
virtual const_iterator begin () const
virtual const_iterator end () const
virtual iterator begin ()
virtual iterator end ()
virtual const_iterator cbegin () const
virtual const_iterator cend () const
bool operator== (const OrdVector &rhs) const
bool operator< (const OrdVector &rhs) const
const std::vector< Key > & to_vector () const
bool is_subset_of (const OrdVector &bigger) const
bool is_intersection_empty_with (const OrdVector &rhs) const
void rename (const std::vector< Key > &renaming)
Static Public Member Functions
static OrdVector with_reserved (const size_t capacity)
Create OrdVector with reserved capacity.
static OrdVector difference (const OrdVector &lhs, const OrdVector &rhs)
static void set_union (const OrdVector &lhs, const OrdVector &rhs, OrdVector &result)
static OrdVector set_union (const OrdVector &lhs, const OrdVector &rhs)
static OrdVector intersection (const OrdVector &lhs, const OrdVector &rhs)
Private Member Functions
bool is_sorted () const
Static Private Member Functions
template<typename T >
static std::string to_str (const T &n)
Converts an object to string.
Private Attributes
VectorType vec_
Friends
std::ostream & operator<< (std::ostream &os, const OrdVector &vec)
Overloaded << operator.
Detailed Description
template<class Key>
class mata::utils::OrdVector< Key >
Implementation of a set using ordered vector.
This class implements the interface of a set (the same interface as std::set) using ordered vector as the underlying data structure.
Template Parameters
Key Key type: type of the elements contained in the container. Each elements in a set is also its key.
Definition at line 49 of file ord-vector.hh.
Member Typedef Documentation
const_iterator
template<class Key > using const_iterator = typename VectorType::const_iterator
Definition at line 57 of file ord-vector.hh.
const_reference
template<class Key > using const_reference = typename VectorType::const_reference
Definition at line 58 of file ord-vector.hh.
iterator
template<class Key > using iterator = typename VectorType::iterator
Definition at line 56 of file ord-vector.hh.
reference
template<class Key > using reference = typename VectorType::reference
Definition at line 59 of file ord-vector.hh.
size_type
template<class Key > using size_type = size_t
Definition at line 55 of file ord-vector.hh.
value_type
template<class Key > using value_type = Key
Definition at line 54 of file ord-vector.hh.
VectorType
template<class Key > using VectorType = std::vector<Key>
Definition at line 53 of file ord-vector.hh.
Constructor & Destructor Documentation
OrdVector() [1/9]
template<class Key > OrdVector () inline
Definition at line 89 of file ord-vector.hh.
OrdVector() [2/9]
template<class Key > OrdVector (const VectorType & vec) inline explicit
Definition at line 90 of file ord-vector.hh.
Referenced by OrdVector< Key >::OrdVector().
OrdVector() [3/9]
template<class Key > OrdVector (const std::set< Key > & set) inline explicit
Definition at line 91 of file ord-vector.hh.
References OrdVector< Key >::OrdVector().
OrdVector() [4/9]
template<class Key > template<class T > OrdVector (const T & set) inline explicit
Definition at line 93 of file ord-vector.hh.
OrdVector() [5/9]
template<class Key > OrdVector (std::initializer_list< Key > list) inline
Definition at line 94 of file ord-vector.hh.
OrdVector() [6/9]
template<class Key > OrdVector (const OrdVector< Key > & rhs) default
OrdVector() [7/9]
template<class Key > OrdVector (OrdVector< Key > && other) inline noexcept
Definition at line 96 of file ord-vector.hh.
OrdVector() [8/9]
template<class Key > OrdVector (const Key & key) inline explicit
Definition at line 97 of file ord-vector.hh.
OrdVector() [9/9]
template<class Key > template<class InputIterator > OrdVector (InputIterator first, InputIterator last) inline explicit
Definition at line 99 of file ord-vector.hh.
~OrdVector()
template<class Key > virtual ~OrdVector () virtual default
Member Function Documentation
at() [1/2]
template<class Key > virtual Key & at (const size_t index) inline virtual
Definition at line 295 of file ord-vector.hh.
at() [2/2]
template<class Key > virtual const Key & at (const size_t index) const inline virtual
Definition at line 294 of file ord-vector.hh.
back() [1/2]
template<class Key > virtual reference back () inline virtual
Get reference to the last element in the vector.
Modifying the underlying value in the reference could break sortedness.
Definition at line 342 of file ord-vector.hh.
back() [2/2]
template<class Key > virtual const_reference back () const inline virtual
Definition at line 335 of file ord-vector.hh.
begin() [1/2]
template<class Key > virtual iterator begin () inline virtual
Definition at line 349 of file ord-vector.hh.
begin() [2/2]
template<class Key > virtual const_iterator begin () const inline virtual
Definition at line 346 of file ord-vector.hh.
cbegin()
template<class Key > virtual const_iterator cbegin () const inline virtual
Definition at line 352 of file ord-vector.hh.
cend()
template<class Key > virtual const_iterator cend () const inline virtual
Definition at line 353 of file ord-vector.hh.
clear()
template<class Key > void clear () inline
Definition at line 219 of file ord-vector.hh.
Referenced by OrdVector< Key >::insert().
contains()
template<class Key > bool contains (const Key & key) const inline
Check whether key exists in the ordered vector.
Definition at line 300 of file ord-vector.hh.
count()
template<class Key > size_t count (const Key & key) const inline
Definition at line 223 of file ord-vector.hh.
difference() [1/2]
template<class Key > static OrdVector difference (const OrdVector< Key > & lhs, const OrdVector< Key > & rhs) inline static
Definition at line 424 of file ord-vector.hh.
difference() [2/2]
template<class Key > OrdVector difference (const OrdVector< Key > & rhs) const inline
Compute set difference as this minus rhs.
Parameters
rhs Other vector with symbols to be excluded.
Returns
this minus rhs.
Definition at line 239 of file ord-vector.hh.
emplace_back()
template<class Key > template<typename... Args> reference emplace_back (Args &&... args) inline
Definition at line 133 of file ord-vector.hh.
empty()
template<class Key > virtual bool empty () const inline virtual
Definition at line 321 of file ord-vector.hh.
Referenced by OrdVector< Key >::set_union().
end() [1/2]
template<class Key > virtual iterator end () inline virtual
Definition at line 350 of file ord-vector.hh.
end() [2/2]
template<class Key > virtual const_iterator end () const inline virtual
Definition at line 347 of file ord-vector.hh.
erase() [1/3]
template<class Key > size_t erase (const Key & k) inline
Remove k from sorted vector.
This function expects the vector to be sorted.
Definition at line 307 of file ord-vector.hh.
erase() [2/3]
template<class Key > virtual iterator erase (const_iterator first, const_iterator last) inline virtual
Definition at line 152 of file ord-vector.hh.
erase() [3/3]
template<class Key > virtual iterator erase (const_iterator pos) inline virtual
Definition at line 151 of file ord-vector.hh.
filter()
template<class Key > template<typename Fun > void filter (const Fun && is_staying) inline
Definition at line 331 of file ord-vector.hh.
filter_indexes()
template<class Key > template<typename Fun > void filter_indexes (const Fun && is_staying) inline
Definition at line 325 of file ord-vector.hh.
find() [1/2]
template<class Key > virtual iterator find (const Key & key) inline virtual
Definition at line 253 of file ord-vector.hh.
find() [2/2]
template<class Key > virtual const_iterator find (const Key & key) const inline virtual
Definition at line 243 of file ord-vector.hh.
front() [1/2]
template<class Key > virtual Key & front () inline virtual
Definition at line 264 of file ord-vector.hh.
front() [2/2]
template<class Key > virtual const Key & front () const inline virtual
Definition at line 263 of file ord-vector.hh.
insert() [1/3]
template<class Key > virtual void insert (const Key & x) inline virtual
Definition at line 154 of file ord-vector.hh.
insert() [2/3]
template<class Key > virtual void insert (const OrdVector< Key > & vec) inline virtual
Definition at line 201 of file ord-vector.hh.
References OrdVector< Key >::clear().
insert() [3/3]
template<class Key > void insert (iterator itr, const Key & x) inline
Definition at line 124 of file ord-vector.hh.
intersection() [1/2]
template<class Key > static OrdVector intersection (const OrdVector< Key > & lhs, const OrdVector< Key > & rhs) inline static
Definition at line 496 of file ord-vector.hh.
intersection() [2/2]
template<class Key > OrdVector intersection (const OrdVector< Key > & rhs) const inline
Definition at line 241 of file ord-vector.hh.
is_intersection_empty_with()
template<class Key > bool is_intersection_empty_with (const OrdVector< Key > & rhs) const inline
Definition at line 395 of file ord-vector.hh.
is_sorted()
template<class Key > bool is_sorted () const inline private
Definition at line 65 of file ord-vector.hh.
is_subset_of()
template<class Key > bool is_subset_of (const OrdVector< Key > & bigger) const inline
Definition at line 391 of file ord-vector.hh.
max() [1/2]
template<class Key > virtual Key & max () inline virtual
Definition at line 287 of file ord-vector.hh.
max() [2/2]
template<class Key > virtual const Key & max () const inline virtual
Definition at line 280 of file ord-vector.hh.
min() [1/2]
template<class Key > virtual Key & min () inline virtual
Definition at line 273 of file ord-vector.hh.
min() [2/2]
template<class Key > virtual const Key & min () const inline virtual
Definition at line 266 of file ord-vector.hh.
operator<()
template<class Key > bool operator< (const OrdVector< Key > & rhs) const inline
Definition at line 383 of file ord-vector.hh.
operator=() [1/2]
template<class Key > OrdVector & operator= (const OrdVector< Key > & other) inline
Definition at line 101 of file ord-vector.hh.
operator=() [2/2]
template<class Key > OrdVector & operator= (OrdVector< Key > && other) inline noexcept
Definition at line 106 of file ord-vector.hh.
operator==()
template<class Key > bool operator== (const OrdVector< Key > & rhs) const inline
Definition at line 377 of file ord-vector.hh.
pop_back()
template<class Key > virtual void pop_back () inline virtual
Definition at line 344 of file ord-vector.hh.
push_back() [1/2]
template<class Key > reference push_back (const Key & t) inline
Definition at line 141 of file ord-vector.hh.
push_back() [2/2]
template<class Key > reference push_back (Key && t) inline
Definition at line 146 of file ord-vector.hh.
rename()
template<class Key > void rename (const std::vector< Key > & renaming) inline
Definition at line 422 of file ord-vector.hh.
reserve()
template<class Key > virtual void reserve (size_t size) inline virtual
Definition at line 148 of file ord-vector.hh.
resize()
template<class Key > virtual void resize (size_t size) inline virtual
Definition at line 149 of file ord-vector.hh.
set_union() [1/2]
template<class Key > static OrdVector set_union (const OrdVector< Key > & lhs, const OrdVector< Key > & rhs) inline static
Definition at line 490 of file ord-vector.hh.
set_union() [2/2]
template<class Key > static void set_union (const OrdVector< Key > & lhs, const OrdVector< Key > & rhs, OrdVector< Key > & result) inline static
Definition at line 451 of file ord-vector.hh.
References OrdVector< Key >::empty().
size()
template<class Key > virtual size_t size () const inline virtual
Definition at line 221 of file ord-vector.hh.
to_str()
template<class Key > template<typename T > static std::string to_str (const T & n) inline static private
Converts an object to string.
Static method for conversion of an object of any class with the << output operator into a string
Parameters
[in] n The object for the conversion.
Returns
The string representation of the object.
Definition at line 77 of file ord-vector.hh.
to_vector()
template<class Key > const std::vector< Key > & to_vector () const inline
Definition at line 389 of file ord-vector.hh.
with_reserved()
template<class Key > static OrdVector with_reserved (const size_t capacity) inline static
Create OrdVector with reserved capacity.
Parameters
[in] capacity Capacity of OrdVector to reserve.
Returns
Newly create OrdVector.
Definition at line 118 of file ord-vector.hh.
Friends And Related Symbol Documentation
operator<<
template<class Key > std::ostream & operator<< (std::ostream & os, const OrdVector< Key > & vec) friend
Overloaded << operator.
Overloaded << operator for output stream.
See also
to_str()
Parameters
[in] os The output stream
[in] vec Assignment to the variables
Returns
Modified output stream
Definition at line 367 of file ord-vector.hh.
Member Data Documentation
vec_
template<class Key > VectorType vec_ private
Definition at line 62 of file ord-vector.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/utils/ord-vector.hh