Mata: EnumAlphabet Class Reference
EnumAlphabet Class Reference
Enumerated alphabet using a set of integers as symbols maintaining a set of specified symbols.
#include <alphabet.hh>
Public Member Functions
EnumAlphabet ()=default
EnumAlphabet (const EnumAlphabet &alphabet)=default
EnumAlphabet (const EnumAlphabet *const alphabet)
EnumAlphabet (EnumAlphabet &&rhs)=default
utils::OrdVector< Symbol > get_alphabet_symbols () const override
Get a set of all symbols in the alphabet.
utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > &symbols) const override
complement of a set of symbols wrt the alphabet
std::string reverse_translate_symbol (Symbol symbol) const override
Translate internal symbol representation back to its original string name.
EnumAlphabet & operator= (const EnumAlphabet &rhs)=default
EnumAlphabet & operator= (EnumAlphabet &&rhs)=default
void add_symbols_from (const mata::utils::OrdVector< Symbol > &symbols)
Expand alphabet by symbols from the passed symbols.
void add_symbols_from (const EnumAlphabet &alphabet)
Expand alphabet by symbols from the passed alphabet.
EnumAlphabet (std::initializer_list< Symbol > symbols)
template<class InputIt >
EnumAlphabet (InputIt first, InputIt last)
EnumAlphabet (std::initializer_list< std::string > l)
Symbol translate_symb (const std::string &str) override
translates a string into a symbol
Word translate_word (const WordName &word_name) const override
Translate sequence of symbol names to sequence of their respective values.
void add_new_symbol (const std::string &symbol)
Add new symbol to the alphabet with the value identical to its string representation.
void add_new_symbol (Symbol symbol)
Add new symbol to the alphabet.
Symbol get_next_value () const
Get the next value for a potential new symbol.
size_t get_number_of_symbols () const
Get the number of existing symbols, epsilon symbols excluded.
bool empty () const override
Checks whether the alphabet has any symbols.
void update_next_symbol_value (Symbol value)
Update next symbol value when appropriate.
size_t erase (const Symbol symbol)
Erase a symbol from the alphabet.
void erase (utils::OrdVector< Symbol >::const_iterator pos)
Remove a symbol name value pair from the position pos from the alphabet.
void erase (utils::OrdVector< Symbol >::const_iterator first, utils::OrdVector< Symbol >::const_iterator last)
Remove a symbol name value pair from the positions between first and last from the alphabet.
void clear () override
Symbol operator[] (const std::string &symb)
also translates strings to symbols
virtual bool is_equal (const Alphabet &other_alphabet) const
Check whether two alphabets are equal.
virtual bool is_equal (const Alphabet *const other_alphabet) const
Check whether two alphabets are equal.
bool operator== (const Alphabet &) const =delete
Protected Member Functions
virtual const void * address () const
Private Attributes
mata::utils::OrdVector< Symbol > symbols_ {}
Map of string transition symbols to symbol values.
Symbol next_symbol_value_ { 0 }
Next value to be used for a newly added symbol.
Detailed Description
Enumerated alphabet using a set of integers as symbols maintaining a set of specified symbols.
EnumAlphabet is a version of direct (identity) alphabet (does not give names to symbols, their name is their integer value directly). However, unlike IntAlphabet, EnumAlphabet maintains an ordered set of symbols in the alphabet.
Therefore, calling member functions get_complement() and get_alphabet_symbols() makes sense in the context of EnumAlphabet and the functions give the expected results.
Example:
Alphabet alph{ EnumAlphabet{ 0, 4, 6, 8, 9 } };
CHECK(alph.translate_symb("6") == 6);
CHECK_THROWS(alph.translate_symb("5")); // Throws an exception about an unknown symbol.
CHECK(alph.get_complement({ utils::OrdVector<Symbol>{ 0, 6, 9 } }) == utils::OrdVector<Symbol>{ 4, 8 });
Definition at line 178 of file alphabet.hh.
Constructor & Destructor Documentation
EnumAlphabet() [1/7]
EnumAlphabet () explicit default
EnumAlphabet() [2/7]
EnumAlphabet (const EnumAlphabet & alphabet) default
Referenced by EnumAlphabet::EnumAlphabet().
EnumAlphabet() [3/7]
EnumAlphabet (const EnumAlphabet *const alphabet) inline explicit
Definition at line 182 of file alphabet.hh.
References EnumAlphabet::EnumAlphabet().
EnumAlphabet() [4/7]
EnumAlphabet (EnumAlphabet && rhs) default
EnumAlphabet() [5/7]
EnumAlphabet (std::initializer_list< Symbol > symbols) inline
Definition at line 210 of file alphabet.hh.
EnumAlphabet() [6/7]
template<class InputIt > EnumAlphabet (InputIt first, InputIt last) inline
Definition at line 211 of file alphabet.hh.
EnumAlphabet() [7/7]
EnumAlphabet (std::initializer_list< std::string > l) inline
Definition at line 214 of file alphabet.hh.
Member Function Documentation
add_new_symbol() [1/2]
void add_new_symbol (const std::string & symbol)
Add new symbol to the alphabet with the value identical to its string representation.
Parameters
[in] symbol User-space representation of the symbol.
Returns
Result of the insertion as InsertionResult.
add_new_symbol() [2/2]
void add_new_symbol (Symbol symbol)
Add new symbol to the alphabet.
Parameters
[in] key User-space representation of the symbol.
[in] symbol Number of the symbol to be used on transitions.
Returns
Result of the insertion as InsertionResult.
add_symbols_from() [1/2]
void add_symbols_from (const EnumAlphabet & alphabet) inline
Expand alphabet by symbols from the passed alphabet.
Parameters
[in] symbols_to_add Vector of symbols to add.
Definition at line 208 of file alphabet.hh.
add_symbols_from() [2/2]
void add_symbols_from (const mata::utils::OrdVector< Symbol > & symbols) inline
Expand alphabet by symbols from the passed symbols.
Adding a symbol name which already exists will throw an exception.
Parameters
[in] symbols Vector of symbols to add.
Definition at line 201 of file alphabet.hh.
address()
virtual const void * address () const inline protected virtual inherited
Reimplemented in IntAlphabet.
Definition at line 93 of file alphabet.hh.
Referenced by Alphabet::is_equal(), and Alphabet::is_equal().
clear()
void clear () inline override virtual
Reimplemented from Alphabet.
Definition at line 284 of file alphabet.hh.
References EnumAlphabet::next_symbol_value_.
empty()
bool empty () const inline override virtual
Checks whether the alphabet has any symbols.
Implements Alphabet.
Definition at line 248 of file alphabet.hh.
erase() [1/3]
size_t erase (const Symbol symbol)
Erase a symbol from the alphabet.
Returns
Number of symbols erased (0 or 1).
erase() [2/3]
void erase (utils::OrdVector< Symbol >::const_iterator first, utils::OrdVector< Symbol >::const_iterator last) inline
Remove a symbol name value pair from the positions between first and last from the alphabet.
Returns
Iterator following the last removed element.
Definition at line 280 of file alphabet.hh.
erase() [3/3]
void erase (utils::OrdVector< Symbol >::const_iterator pos) inline
Remove a symbol name value pair from the position pos from the alphabet.
Returns
Iterator following the last removed element.
Definition at line 274 of file alphabet.hh.
get_alphabet_symbols()
utils::OrdVector< Symbol > get_alphabet_symbols () const inline override virtual
Get a set of all symbols in the alphabet.
The result does not have to equal the list of symbols in the automaton using this alphabet.
Reimplemented from Alphabet.
Definition at line 185 of file alphabet.hh.
get_complement()
utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > & symbols) const inline override virtual
complement of a set of symbols wrt the alphabet
Reimplemented from Alphabet.
Definition at line 186 of file alphabet.hh.
get_next_value()
Symbol get_next_value () const inline
Get the next value for a potential new symbol.
Returns
Next Symbol value.
Definition at line 240 of file alphabet.hh.
References EnumAlphabet::next_symbol_value_.
get_number_of_symbols()
size_t get_number_of_symbols () const inline
Get the number of existing symbols, epsilon symbols excluded.
Returns
The number of symbols.
Definition at line 246 of file alphabet.hh.
is_equal() [1/2]
virtual bool is_equal (const Alphabet & other_alphabet) const inline virtual inherited
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 70 of file alphabet.hh.
References Alphabet::address().
is_equal() [2/2]
virtual bool is_equal (const Alphabet *const other_alphabet) const inline virtual inherited
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 79 of file alphabet.hh.
References Alphabet::address().
operator=() [1/2]
EnumAlphabet & operator= (const EnumAlphabet & rhs) default
operator=() [2/2]
EnumAlphabet & operator= (EnumAlphabet && rhs) default
operator==()
bool operator== (const Alphabet &) const delete inherited
operator[]()
Symbol operator[] (const std::string & symb) inline inherited
also translates strings to symbols
Definition at line 46 of file alphabet.hh.
References Alphabet::translate_symb().
reverse_translate_symbol()
std::string reverse_translate_symbol (Symbol symbol) const override virtual
Translate internal symbol representation back to its original string name.
Throws an exception when the symbol is missing in the alphabet.
Parameters
[in] symbol Symbol to translate.
Returns
symbol original name.
Implements Alphabet.
translate_symb()
Symbol translate_symb (const std::string & symb) override virtual
translates a string into a symbol
Implements Alphabet.
translate_word()
Word translate_word (const WordName & word_name) const override virtual
Translate sequence of symbol names to sequence of their respective values.
Reimplemented from Alphabet.
update_next_symbol_value()
void update_next_symbol_value (Symbol value)
Update next symbol value when appropriate.
When the newly inserted value is larger or equal to the current next symbol value, update the next symbol value to a value one larger than the new value.
Parameters
value The value of the newly added symbol.
Member Data Documentation
next_symbol_value_
Symbol next_symbol_value_ { 0 } private
Next value to be used for a newly added symbol.
Definition at line 252 of file alphabet.hh.
Referenced by EnumAlphabet::clear(), and EnumAlphabet::get_next_value().
symbols_
mata::utils::OrdVector<Symbol> symbols_ {} private
Map of string transition symbols to symbol values.
Definition at line 251 of file alphabet.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/alphabet.hh