Mata: IntAlphabet Class Reference
IntAlphabet Class Reference
Direct alphabet (also identity alphabet or integer alphabet) using integers as symbols.
#include <alphabet.hh>
Classes
class IntAlphabetSingleton
Singleton class implementing integer alphabet_instance for class IntAlphabet.
Public Member Functions
IntAlphabet ()
Symbol translate_symb (const std::string &symb) override
translates a string into a symbol
std::string reverse_translate_symbol (Symbol symbol) const override
Translate internal symbol representation back to its original string name.
utils::OrdVector< Symbol > get_alphabet_symbols () const override
Get a set of all symbols in the alphabet.
utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > &symbols) const override
complement of a set of symbols wrt the alphabet
IntAlphabet (const IntAlphabet &)=default
IntAlphabet & operator= (const IntAlphabet &int_alphabet)=delete
bool empty () const override
Checks whether the alphabet has any symbols.
void clear () override
virtual Word translate_word (const WordName &word_name) const
Translate sequence of symbol names to sequence of their respective values.
Symbol operator[] (const std::string &symb)
also translates strings to symbols
virtual bool is_equal (const Alphabet &other_alphabet) const
Check whether two alphabets are equal.
virtual bool is_equal (const Alphabet *const other_alphabet) const
Check whether two alphabets are equal.
bool operator== (const Alphabet &) const =delete
Protected Member Functions
const void * address () const override
Private Attributes
IntAlphabetSingleton & alphabet_instance
Detailed Description
Direct alphabet (also identity alphabet or integer alphabet) using integers as symbols.
This alphabet presumes that all integers are valid symbols. Therefore, calling member functions get_complement() and get_alphabet_symbols() makes no sense in this context and the methods will throw exceptions warning about the inappropriate use of IntAlphabet. If one needs these functions, they should use OnTheFlyAlphabet instead of IntAlphabet.
Definition at line 104 of file alphabet.hh.
Constructor & Destructor Documentation
IntAlphabet() [1/2]
IntAlphabet () inline
Definition at line 106 of file alphabet.hh.
References IntAlphabet::alphabet_instance, and IntAlphabet::IntAlphabetSingleton::get().
IntAlphabet() [2/2]
IntAlphabet (const IntAlphabet &) default
Member Function Documentation
address()
const void * address () const inline override protected virtual
Reimplemented from Alphabet.
Definition at line 130 of file alphabet.hh.
References IntAlphabet::alphabet_instance.
clear()
void clear () inline override virtual
Reimplemented from Alphabet.
Definition at line 127 of file alphabet.hh.
empty()
bool empty () const inline override virtual
Checks whether the alphabet has any symbols.
Implements Alphabet.
Definition at line 125 of file alphabet.hh.
get_alphabet_symbols()
utils::OrdVector< Symbol > get_alphabet_symbols () const inline override virtual
Get a set of all symbols in the alphabet.
The result does not have to equal the list of symbols in the automaton using this alphabet.
Reimplemented from Alphabet.
Definition at line 112 of file alphabet.hh.
get_complement()
utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > & symbols) const inline override virtual
complement of a set of symbols wrt the alphabet
Reimplemented from Alphabet.
Definition at line 116 of file alphabet.hh.
is_equal() [1/2]
virtual bool is_equal (const Alphabet & other_alphabet) const inline virtual inherited
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 70 of file alphabet.hh.
References Alphabet::address().
is_equal() [2/2]
virtual bool is_equal (const Alphabet *const other_alphabet) const inline virtual inherited
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 79 of file alphabet.hh.
References Alphabet::address().
operator=()
IntAlphabet & operator= (const IntAlphabet & int_alphabet) delete
operator==()
bool operator== (const Alphabet &) const delete inherited
operator[]()
Symbol operator[] (const std::string & symb) inline inherited
also translates strings to symbols
Definition at line 46 of file alphabet.hh.
References Alphabet::translate_symb().
reverse_translate_symbol()
std::string reverse_translate_symbol (Symbol symbol) const inline override virtual
Translate internal symbol representation back to its original string name.
Throws an exception when the symbol is missing in the alphabet.
Parameters
[in] symbol Symbol to translate.
Returns
symbol original name.
Implements Alphabet.
Definition at line 110 of file alphabet.hh.
translate_symb()
Symbol translate_symb (const std::string & symb) override virtual
translates a string into a symbol
Implements Alphabet.
translate_word()
virtual Word translate_word (const WordName & word_name) const inline virtual inherited
Translate sequence of symbol names to sequence of their respective values.
Reimplemented in EnumAlphabet, and OnTheFlyAlphabet.
Definition at line 31 of file alphabet.hh.
Member Data Documentation
alphabet_instance
IntAlphabetSingleton& alphabet_instance private
Definition at line 157 of file alphabet.hh.
Referenced by IntAlphabet::address(), and IntAlphabet::IntAlphabet().
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/alphabet.hh