Mata: OnTheFlyAlphabet Class Reference
OnTheFlyAlphabet Class Reference
An alphabet constructed 'on the fly'.
#include <alphabet.hh>
Public Types
using StringToSymbolMap = std::unordered_map< std::string, Symbol >
using InsertionResult = std::pair< StringToSymbolMap::const_iterator, bool >
Result of the insertion of a new symbol.
Public Member Functions
OnTheFlyAlphabet (Symbol init_symbol=0)
OnTheFlyAlphabet (const OnTheFlyAlphabet &alphabet)=default
OnTheFlyAlphabet (OnTheFlyAlphabet &&alphabet)=default
OnTheFlyAlphabet (const OnTheFlyAlphabet *const alphabet)
OnTheFlyAlphabet (StringToSymbolMap str_sym_map)
OnTheFlyAlphabet (const std::vector< std::string > &symbol_names, Symbol init_symbol=0)
Create alphabet from a list of symbol names.
template<class InputIt >
OnTheFlyAlphabet (InputIt first, InputIt last)
OnTheFlyAlphabet (std::initializer_list< std::pair< std::string, Symbol > > name_symbol_map)
utils::OrdVector< Symbol > get_alphabet_symbols () const override
Get a set of all symbols in the alphabet.
utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > &symbols) const override
complement of a set of symbols wrt the alphabet
std::string reverse_translate_symbol (Symbol symbol) const override
Translate internal symbol representation back to its original string name.
OnTheFlyAlphabet & operator= (const OnTheFlyAlphabet &rhs)=default
OnTheFlyAlphabet & operator= (OnTheFlyAlphabet &&rhs)=default
void add_symbols_from (const std::vector< std::string > &symbol_names)
Expand alphabet by symbols from the passed symbol_names.
void add_symbols_from (const StringToSymbolMap &new_symbol_map)
Expand alphabet by symbols from the passed symbol_map.
Symbol translate_symb (const std::string &str) override
translates a string into a symbol
virtual Word translate_word (const WordName &word_name) const override
Translate sequence of symbol names to sequence of their respective values.
InsertionResult add_new_symbol (const std::string &key)
Add new symbol to the alphabet with the value of next_symbol_value.
InsertionResult add_new_symbol (const std::string &key, Symbol value)
Add new symbol to the alphabet.
InsertionResult try_add_new_symbol (const std::string &key, Symbol value)
Try to add symbol to the alphabet map.
Symbol get_next_value () const
Get the next value for a potential new symbol.
size_t get_number_of_symbols () const
Get the number of existing symbols, epsilon symbols excluded.
const StringToSymbolMap & get_symbol_map () const
Get the symbol map used in the alphabet.
bool empty () const override
Checks whether the alphabet has any symbols.
void update_next_symbol_value (Symbol value)
Update next symbol value when appropriate.
size_t erase (Symbol symbol)
Remove a symbol name value pair specified by its symbol from the alphabet.
size_t erase (const std::string &symbol_name)
Remove a symbol name value pair specified by its symbol_name from the alphabet.
void erase (StringToSymbolMap::const_iterator pos)
Remove a symbol name value pair from the position pos from the alphabet.
void erase (StringToSymbolMap::const_iterator first, StringToSymbolMap::const_iterator last)
Remove a symbol name value pair from the positions between first and last from the alphabet.
void clear () override
Symbol operator[] (const std::string &symb)
also translates strings to symbols
virtual bool is_equal (const Alphabet &other_alphabet) const
Check whether two alphabets are equal.
virtual bool is_equal (const Alphabet *const other_alphabet) const
Check whether two alphabets are equal.
bool operator== (const Alphabet &) const =delete
Protected Member Functions
virtual const void * address () const
Private Attributes
StringToSymbolMap symbol_map_ {}
Map of string transition symbols to symbol values.
Symbol next_symbol_value_ {}
Next value to be used for a newly added symbol.
Detailed Description
An alphabet constructed 'on the fly'.
Should be use anytime the automata have a specific names for the symbols.
Definition at line 291 of file alphabet.hh.
Member Typedef Documentation
InsertionResult
using InsertionResult = std::pair<StringToSymbolMap::const_iterator, bool>
Result of the insertion of a new symbol.
Definition at line 296 of file alphabet.hh.
StringToSymbolMap
using StringToSymbolMap = std::unordered_map<std::string, Symbol>
Definition at line 293 of file alphabet.hh.
Constructor & Destructor Documentation
OnTheFlyAlphabet() [1/8]
OnTheFlyAlphabet (Symbol init_symbol = 0) inline explicit
Definition at line 298 of file alphabet.hh.
References OnTheFlyAlphabet::next_symbol_value_.
Referenced by mata::nfa::builder::construct(), mata::nft::builder::construct(), mata::nfa::plumbing::construct(), mata::nft::plumbing::construct(), mata::nfa::create_alphabet(), mata::nfa::builder::create_sigma_star_nfa(), and mata::nft::builder::create_sigma_star_nft().
OnTheFlyAlphabet() [2/8]
OnTheFlyAlphabet (const OnTheFlyAlphabet & alphabet) default
Referenced by OnTheFlyAlphabet::OnTheFlyAlphabet().
OnTheFlyAlphabet() [3/8]
OnTheFlyAlphabet (OnTheFlyAlphabet && alphabet) default
OnTheFlyAlphabet() [4/8]
OnTheFlyAlphabet (const OnTheFlyAlphabet *const alphabet) inline explicit
Definition at line 301 of file alphabet.hh.
References OnTheFlyAlphabet::OnTheFlyAlphabet().
OnTheFlyAlphabet() [5/8]
OnTheFlyAlphabet (StringToSymbolMap str_sym_map) inline explicit
Definition at line 302 of file alphabet.hh.
OnTheFlyAlphabet() [6/8]
OnTheFlyAlphabet (const std::vector< std::string > & symbol_names, Symbol init_symbol = 0) inline explicit
Create alphabet from a list of symbol names.
Parameters
symbol_names Names for symbols on transitions.
init_symbol Start of a sequence of values to use for new symbols.
Definition at line 309 of file alphabet.hh.
References OnTheFlyAlphabet::next_symbol_value_, and OnTheFlyAlphabet::OnTheFlyAlphabet().
Referenced by OnTheFlyAlphabet::OnTheFlyAlphabet().
OnTheFlyAlphabet() [7/8]
template<class InputIt > OnTheFlyAlphabet (InputIt first, InputIt last) inline
Definition at line 312 of file alphabet.hh.
OnTheFlyAlphabet() [8/8]
OnTheFlyAlphabet (std::initializer_list< std::pair< std::string, Symbol > > name_symbol_map) inline
Definition at line 317 of file alphabet.hh.
Member Function Documentation
add_new_symbol() [1/2]
InsertionResult add_new_symbol (const std::string & key)
Add new symbol to the alphabet with the value of next_symbol_value.
Throws an exception when the adding fails.
Parameters
[in] key User-space representation of the symbol.
Returns
Result of the insertion as InsertionResult.
add_new_symbol() [2/2]
InsertionResult add_new_symbol (const std::string & key, Symbol value)
Add new symbol to the alphabet.
Throws an exception when the adding fails.
Parameters
[in] key User-space representation of the symbol.
[in] value Number of the symbol to be used on transitions.
Returns
Result of the insertion as InsertionResult.
add_symbols_from() [1/2]
void add_symbols_from (const std::vector< std::string > & symbol_names)
Expand alphabet by symbols from the passed symbol_names.
Adding a symbol name which already exists will throw an exception.
Parameters
[in] symbol_names Vector of symbol names.
add_symbols_from() [2/2]
void add_symbols_from (const StringToSymbolMap & new_symbol_map)
Expand alphabet by symbols from the passed symbol_map.
The value of the already existing symbols will NOT be overwritten.
Parameters
[in] new_symbol_map Map of strings to symbols.
address()
virtual const void * address () const inline protected virtual inherited
Reimplemented in IntAlphabet.
Definition at line 93 of file alphabet.hh.
Referenced by Alphabet::is_equal(), and Alphabet::is_equal().
clear()
void clear () inline override virtual
Reimplemented from Alphabet.
Definition at line 444 of file alphabet.hh.
References OnTheFlyAlphabet::next_symbol_value_.
empty()
bool empty () const inline override virtual
Checks whether the alphabet has any symbols.
Implements Alphabet.
Definition at line 402 of file alphabet.hh.
erase() [1/4]
size_t erase (const std::string & symbol_name)
Remove a symbol name value pair specified by its symbol_name from the alphabet.
Returns
Number of symbols removed (0 or 1).
erase() [2/4]
void erase (StringToSymbolMap::const_iterator first, StringToSymbolMap::const_iterator last) inline
Remove a symbol name value pair from the positions between first and last from the alphabet.
Definition at line 440 of file alphabet.hh.
erase() [3/4]
void erase (StringToSymbolMap::const_iterator pos) inline
Remove a symbol name value pair from the position pos from the alphabet.
Definition at line 435 of file alphabet.hh.
erase() [4/4]
size_t erase (Symbol symbol)
Remove a symbol name value pair specified by its symbol from the alphabet.
Warning
Complexity: O(n), where n is the number of symbols in the alphabet.
Returns
Number of symbols removed (0 or 1).
get_alphabet_symbols()
utils::OrdVector< Symbol > get_alphabet_symbols () const override virtual
Get a set of all symbols in the alphabet.
The result does not have to equal the list of symbols in the automaton using this alphabet.
Reimplemented from Alphabet.
get_complement()
utils::OrdVector< Symbol > get_complement (const utils::OrdVector< Symbol > & symbols) const override virtual
complement of a set of symbols wrt the alphabet
Reimplemented from Alphabet.
get_next_value()
Symbol get_next_value () const inline
Get the next value for a potential new symbol.
Returns
Next Symbol value.
Definition at line 388 of file alphabet.hh.
References OnTheFlyAlphabet::next_symbol_value_.
get_number_of_symbols()
size_t get_number_of_symbols () const inline
Get the number of existing symbols, epsilon symbols excluded.
Returns
The number of symbols.
Definition at line 394 of file alphabet.hh.
References OnTheFlyAlphabet::next_symbol_value_.
get_symbol_map()
const StringToSymbolMap & get_symbol_map () const inline
Get the symbol map used in the alphabet.
Returns
Map mapping strings to symbols used internally in Mata.
Definition at line 400 of file alphabet.hh.
is_equal() [1/2]
virtual bool is_equal (const Alphabet & other_alphabet) const inline virtual inherited
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 70 of file alphabet.hh.
References Alphabet::address().
is_equal() [2/2]
virtual bool is_equal (const Alphabet *const other_alphabet) const inline virtual inherited
Check whether two alphabets are equal.
In general, two alphabets are equal if and only if they are of the same class instance.
Parameters
other_alphabet The other alphabet to compare with for equality.
Returns
True if equal, false otherwise.
Definition at line 79 of file alphabet.hh.
References Alphabet::address().
operator=() [1/2]
OnTheFlyAlphabet & operator= (const OnTheFlyAlphabet & rhs) default
operator=() [2/2]
OnTheFlyAlphabet & operator= (OnTheFlyAlphabet && rhs) default
operator==()
bool operator== (const Alphabet &) const delete inherited
operator[]()
Symbol operator[] (const std::string & symb) inline inherited
also translates strings to symbols
Definition at line 46 of file alphabet.hh.
References Alphabet::translate_symb().
reverse_translate_symbol()
std::string reverse_translate_symbol (Symbol symbol) const override virtual
Translate internal symbol representation back to its original string name.
Throws an exception when the symbol is missing in the alphabet.
Parameters
[in] symbol Symbol to translate.
Returns
symbol original name.
Implements Alphabet.
translate_symb()
Symbol translate_symb (const std::string & symb) override virtual
translates a string into a symbol
Implements Alphabet.
translate_word()
virtual Word translate_word (const WordName & word_name) const override virtual
Translate sequence of symbol names to sequence of their respective values.
Reimplemented from Alphabet.
try_add_new_symbol()
InsertionResult try_add_new_symbol (const std::string & key, Symbol value) inline
Try to add symbol to the alphabet map.
Does not throw an exception when the adding fails.
Parameters
[in] key User-space representation of the symbol.
[in] value Number of the symbol to be used on transitions.
Returns
Result of the insertion as InsertionResult.
Definition at line 382 of file alphabet.hh.
update_next_symbol_value()
void update_next_symbol_value (Symbol value)
Update next symbol value when appropriate.
When the newly inserted value is larger or equal to the current next symbol value, update the next symbol value to a value one larger than the new value.
Parameters
value The value of the newly added symbol.
Member Data Documentation
next_symbol_value_
Symbol next_symbol_value_ {} private
Next value to be used for a newly added symbol.
Definition at line 406 of file alphabet.hh.
Referenced by OnTheFlyAlphabet::clear(), OnTheFlyAlphabet::get_next_value(), OnTheFlyAlphabet::get_number_of_symbols(), OnTheFlyAlphabet::OnTheFlyAlphabet(), and OnTheFlyAlphabet::OnTheFlyAlphabet().
symbol_map_
StringToSymbolMap symbol_map_ {} private
Map of string transition symbols to symbol values.
Definition at line 405 of file alphabet.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/alphabet.hh