Mata: Delta Class Reference
Delta Class Reference
Delta is a data structure for representing transition relation.
#include <delta.hh>
Classes
class Transitions
Iterator over transitions represented as Transition instances.
Public Types
using const_iterator = std::vector< StatePost >::const_iterator
Public Member Functions
Delta ()
Delta (const Delta &other)=default
Delta (Delta &&other)=default
Delta (size_t n)
Delta & operator= (const Delta &other)=default
Delta & operator= (Delta &&other)=default
bool operator== (const Delta &other) const
void reserve (size_t n)
const StatePost & state_post (const State source) const
Get constant reference to the state post of source.
const StatePost & operator[] (const State source) const
Get constant reference to the state post of source.
StatePost & mutable_state_post (State source)
Get mutable (non-constant) reference to the state post of source.
void defragment (const BoolVector &is_staying, const std::vector< State > &renaming)
template<typename... Args>
StatePost & emplace_back (Args &&... args)
void clear ()
void allocate (const size_t num_of_states)
Allocate state posts up to num_of_states states, creating empty StatePost for yet unallocated state posts.
size_t num_of_states () const
bool uses_state (const State state) const
Check whether the state is used in Delta.
size_t num_of_transitions () const
void add (State source, Symbol symbol, State target)
void add (const Transition &trans)
void remove (State source, Symbol symbol, State target)
void remove (const Transition &transition)
bool contains (State source, Symbol symbol, State target) const
Check whether Delta contains a passed transition.
bool contains (const Transition &transition) const
Check whether Delta contains a transition passed as a triple.
bool empty () const
Check whether automaton contains no transitions.
void append (const std::vector< StatePost > &post_vector)
Append post vector to the delta.
std::vector< StatePost > renumber_targets (const std::function< State(State)> &target_renumberer) const
Copy posts of delta and apply a lambda update function on each state from targets.
void add (const State source, const Symbol symbol, const StateSet &targets)
Add transitions to multiple destinations.
const_iterator cbegin () const
const_iterator cend () const
const_iterator begin () const
const_iterator end () const
Transitions transitions () const
Iterator over transitions represented as Transition instances.
std::vector< Transition > get_transitions_to (State state_to) const
Get transitions leading to state_to.
std::vector< Transition > get_transitions_between (State state_from, State state_to) const
Get transitions from state_from to state_to.
StateSet get_successors (State state) const
Get the set of states that are successors of the given state.
const StateSet & get_successors (State state, Symbol symbol) const
StateSet get_successors (State state, Symbol symbol, EpsilonClosureOpt epsilon_closure_opt) const
StatePost::const_iterator epsilon_symbol_posts (State state, Symbol epsilon=EPSILON) const
Iterate over epsilon symbol posts under the given state.
void add_symbols_to (OnTheFlyAlphabet &target_alphabet) const
Expand target_alphabet by symbols from this delta.
utils::OrdVector< Symbol > get_used_symbols () const
Get the set of symbols used on the transitions in the automaton.
utils::OrdVector< Symbol > get_used_symbols_vec () const
std::set< Symbol > get_used_symbols_set () const
utils::SparseSet< Symbol > get_used_symbols_sps () const
std::vector< bool > get_used_symbols_bv () const
BoolVector get_used_symbols_chv () const
Symbol get_max_symbol () const
Get the maximum non-epsilon used symbol.
Static Public Member Functions
static StatePost::const_iterator epsilon_symbol_posts (const StatePost &state_post, Symbol epsilon=EPSILON)
Iterate over epsilon symbol posts under the given state_post.
Static Public Attributes
static const StatePost empty_state_post
Protected Attributes
std::vector< StatePost > state_posts_
Detailed Description
Delta is a data structure for representing transition relation.
Transition is represented as a triple Trans(source state, symbol, target state). Move is the part (symbol, target state), specified for a single source state. Its underlying data structure is vector of StatePost classes. Each index to the vector corresponds to one source state, that is, a number for a certain state is an index to the vector of state posts. Transition relation (delta) in Mata stores a set of transitions in a four-level hierarchical structure: Delta, StatePost, SymbolPost, and a set of target states. A vector of 'StatePost's indexed by a source states on top, where the StatePost for a state 'q' (whose number is 'q' and it is the index to the vector of 'StatePost's) stores a set of 'Move's from the source state 'q'. Namely, 'StatePost' has a vector of 'SymbolPost's, where each 'SymbolPost' stores a symbol 'a' and a vector of target states of 'a'-moves from state 'q'. 'SymbolPost's are ordered by the symbol, target states are ordered by the state number.
Definition at line 311 of file delta.hh.
Member Typedef Documentation
const_iterator
using const_iterator = std::vector<StatePost>::const_iterator
Definition at line 464 of file delta.hh.
Constructor & Destructor Documentation
Delta() [1/4]
Delta () inline
Definition at line 315 of file delta.hh.
Referenced by Nfa::Nfa(), and Nft::Nft().
Delta() [2/4]
Delta (const Delta & other) default
Delta() [3/4]
Delta (Delta && other) default
Delta() [4/4]
Delta (size_t n) inline explicit
Definition at line 318 of file delta.hh.
Member Function Documentation
add() [1/3]
void add (const State source, const Symbol symbol, const StateSet & targets)
Add transitions to multiple destinations.
Parameters
source From
symbol Symbol
targets Set of states to
add() [2/3]
void add (const Transition & trans) inline
Definition at line 413 of file delta.hh.
References Delta::add(), Transition::source, Transition::symbol, and Transition::target.
add() [3/3]
void add (State source, Symbol symbol, State target)
Referenced by Delta::add().
add_symbols_to()
void add_symbols_to (OnTheFlyAlphabet & target_alphabet) const
Expand target_alphabet by symbols from this delta.
The value of the already existing symbols will NOT be overwritten.
allocate()
void allocate (const size_t num_of_states) inline
Allocate state posts up to num_of_states states, creating empty StatePost for yet unallocated state posts.
Parameters
[in] num_of_states Number of states in Delta to allocate state posts for. Have to be at least num_of_states() + 1.
Definition at line 392 of file delta.hh.
append()
void append (const std::vector< StatePost > & post_vector) inline
Append post vector to the delta.
Parameters
post_vector Vector of posts to be appended.
Definition at line 437 of file delta.hh.
begin()
const_iterator begin () const inline
Definition at line 467 of file delta.hh.
cbegin()
const_iterator cbegin () const inline
Definition at line 465 of file delta.hh.
cend()
const_iterator cend () const inline
Definition at line 466 of file delta.hh.
clear()
void clear () inline
Definition at line 383 of file delta.hh.
contains() [1/2]
bool contains (const Transition & transition) const
Check whether Delta contains a transition passed as a triple.
contains() [2/2]
bool contains (State source, Symbol symbol, State target) const
Check whether Delta contains a passed transition.
defragment()
void defragment (const BoolVector & is_staying, const std::vector< State > & renaming)
emplace_back()
template<typename... Args> StatePost & emplace_back (Args &&... args) inline
Definition at line 378 of file delta.hh.
empty()
bool empty () const
Check whether automaton contains no transitions.
Returns
True if there are no transitions in the automaton, false otherwise.
end()
const_iterator end () const inline
Definition at line 468 of file delta.hh.
epsilon_symbol_posts() [1/2]
static StatePost::const_iterator epsilon_symbol_posts (const StatePost & state_post, Symbol epsilon = EPSILON) static
Iterate over epsilon symbol posts under the given state_post.
Parameters
[in] state_post State post from which epsilon transitions are checked.
[in] epsilon User can define his favourite epsilon or used default.
Returns
An iterator to SymbolPost with epsilon symbol. End iterator when there are no epsilon transitions.
epsilon_symbol_posts() [2/2]
StatePost::const_iterator epsilon_symbol_posts (State state, Symbol epsilon = EPSILON) const
Iterate over epsilon symbol posts under the given state.
Parameters
[in] state State from which epsilon transitions are checked.
[in] epsilon User can define his favourite epsilon or used default.
Returns
An iterator to SymbolPost with epsilon symbol. End iterator when there are no epsilon transitions.
get_max_symbol()
Symbol get_max_symbol () const
Get the maximum non-epsilon used symbol.
get_successors() [1/3]
StateSet get_successors (State state) const
Get the set of states that are successors of the given state.
Parameters
[in] state State from which successors are checked.
Returns
Set of states that are successors of the given state.
get_successors() [2/3]
const StateSet & get_successors (State state, Symbol symbol) const
get_successors() [3/3]
StateSet get_successors (State state, Symbol symbol, EpsilonClosureOpt epsilon_closure_opt) const
get_transitions_between()
std::vector< Transition > get_transitions_between (State state_from, State state_to) const
Get transitions from state_from to state_to.
Parameters
state_from[in] Source state.
state_from[in] Target state.
Returns
Transitions from source to state_to.
Operation is slow, traverses over all symbol posts.
get_transitions_to()
std::vector< Transition > get_transitions_to (State state_to) const
Get transitions leading to state_to.
Parameters
state_to[in] Target state for transitions to get.
Returns
Transitions leading to state_to.
Operation is slow, traverses over all symbol posts.
get_used_symbols()
utils::OrdVector< Symbol > get_used_symbols () const
Get the set of symbols used on the transitions in the automaton.
Does not necessarily have to equal the set of symbols in the alphabet used by the automaton.
Returns
Set of symbols used on the transitions.
get_used_symbols_bv()
std::vector< bool > get_used_symbols_bv () const
get_used_symbols_chv()
BoolVector get_used_symbols_chv () const
get_used_symbols_set()
std::set< Symbol > get_used_symbols_set () const
get_used_symbols_sps()
utils::SparseSet< Symbol > get_used_symbols_sps () const
get_used_symbols_vec()
utils::OrdVector< Symbol > get_used_symbols_vec () const
mutable_state_post()
StatePost & mutable_state_post (State source)
Get mutable (non-constant) reference to the state post of source.
The function allows modifying the state post.
BEWARE, IT HAS A SIDE EFFECT.
If we try to access a state post of a source which is present in the automaton as an initial/final state, yet does not have allocated space in Delta, a new state post for source will be allocated along with all state posts for all previous states. This in turn may cause that the entire post data structure is re-allocated. Iterators to Delta will get invalidated. Use the constant 'state_post()' is possible. Or, to prevent the side effect from causing issues, one might want to make sure that posts of all states in the automaton are allocated, e.g., write an NFA method that allocate Delta for all states of the NFA.
Parameters
source[in] Source state of a state post to access.
Returns
State post of source.
num_of_states()
size_t num_of_states () const inline
Returns
Number of states in the whole Delta, including both source and target states.
Definition at line 400 of file delta.hh.
num_of_transitions()
size_t num_of_transitions () const
Returns
Number of transitions in Delta.
operator=() [1/2]
Delta & operator= (const Delta & other) default
operator=() [2/2]
Delta & operator= (Delta && other) default
operator==()
bool operator== (const Delta & other) const
operator[]()
const StatePost & operator[] (const State source) const inline
Get constant reference to the state post of source.
If we try to access a state post of a source which is present in the automaton as an initial/final state, yet does not have allocated space in Delta, an empty_post is returned. Hence, the function has no side effects (no allocation is performed; iterators remain valid).
Parameters
source[in] Source state of a state post to access.
Returns
State post of source.
Definition at line 354 of file delta.hh.
References Delta::state_post().
remove() [1/2]
void remove (const Transition & transition) inline
Definition at line 415 of file delta.hh.
References Delta::remove(), Transition::source, Transition::symbol, and Transition::target.
remove() [2/2]
void remove (State source, Symbol symbol, State target)
Referenced by Delta::remove().
renumber_targets()
std::vector< StatePost > renumber_targets (const std::function< State(State)> & target_renumberer) const
Copy posts of delta and apply a lambda update function on each state from targets.
IMPORTANT: In order to work properly, the lambda function needs to be monotonic, that is, the order of states in targets cannot change.
Parameters
target_renumberer Monotonic lambda function mapping states to different states.
Returns
std::vector<Post> Copied posts.
reserve()
void reserve (size_t n) inline
Definition at line 325 of file delta.hh.
state_post()
const StatePost & state_post (const State source) const inline
Get constant reference to the state post of source.
If we try to access a state post of a source which is present in the automaton as an initial/final state, yet does not have allocated space in Delta, an empty_post is returned. Hence, the function has no side effects (no allocation is performed; iterators remain valid).
Parameters
source[in] Source state of a state post to access.
Returns
State post of source.
Definition at line 338 of file delta.hh.
References Delta::empty_state_post.
Referenced by Delta::operator[]().
transitions()
Transitions transitions () const
Iterator over transitions represented as Transition instances.
uses_state()
bool uses_state (const State state) const inline
Check whether the state is used in Delta.
Definition at line 405 of file delta.hh.
Member Data Documentation
empty_state_post
const StatePost empty_state_post inline static
Definition at line 313 of file delta.hh.
Referenced by Delta::state_post().
state_posts_
std::vector<StatePost> state_posts_ protected
Definition at line 549 of file delta.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/nfa/delta.hh