Mata: ShortestWordsMap Class Reference
ShortestWordsMap Class Reference
Class mapping states to the shortest words accepted by languages of the states.
#include <strings.hh>
Public Member Functions
ShortestWordsMap (const Nfa &aut)
Maps states in the automaton aut to shortest words accepted by languages of the states.
std::set< Word > get_shortest_words_from (const StateSet &states) const
Gets shortest words for the given states.
std::set< Word > get_shortest_words_from (State state) const
Gets shortest words for the given state.
Private Types
using WordLength = int
A length of a word. Pair binding the length of all words in the word set and word set with words of the given length.
using LengthWordsPair = std::pair< WordLength, std::set< Word > >
Private Member Functions
void insert_initial_lengths ()
Inserts initial lengths into the shortest words map.
void compute ()
Computes shortest words for all states in the automaton.
void compute_for_state (State state)
Computes shortest words for the given state.
LengthWordsPair map_default_shortest_words (const State state)
Creates default shortest words mapping for yet unprocessed state.
Static Private Member Functions
static void update_current_words (LengthWordsPair &act, const LengthWordsPair &dst, Symbol symbol)
Update words for the current state.
Private Attributes
std::unordered_map< State, LengthWordsPair > shortest_words_map {}
Map mapping states to the shortest words accepted by the automaton from the mapped state.
std::set< State > processed {}
Set of already processed states.
std::deque< State > fifo_queue {}
FIFO queue for states to process.
const Nfa reversed_automaton
Reversed input automaton.
Detailed Description
Class mapping states to the shortest words accepted by languages of the states.
Definition at line 28 of file strings.hh.
Member Typedef Documentation
LengthWordsPair
using LengthWordsPair = std::pair<WordLength, std::set<Word> > private
Definition at line 56 of file strings.hh.
WordLength
using WordLength = int private
A length of a word. Pair binding the length of all words in the word set and word set with words of the given length.
Definition at line 54 of file strings.hh.
Constructor & Destructor Documentation
ShortestWordsMap()
ShortestWordsMap (const Nfa & aut) inline explicit
Maps states in the automaton aut to shortest words accepted by languages of the states.
Parameters
aut Automaton to compute shortest words for.
Definition at line 34 of file strings.hh.
References ShortestWordsMap::compute(), and ShortestWordsMap::insert_initial_lengths().
Member Function Documentation
compute()
void compute () private
Computes shortest words for all states in the automaton.
Referenced by ShortestWordsMap::ShortestWordsMap().
compute_for_state()
void compute_for_state (State state) private
Computes shortest words for the given state.
Parameters
[in] state State to compute shortest words for.
get_shortest_words_from() [1/2]
std::set< Word > get_shortest_words_from (const StateSet & states) const
Gets shortest words for the given states.
Parameters
[in] states States to map shortest words for.
Returns
Set of shortest words.
get_shortest_words_from() [2/2]
std::set< Word > get_shortest_words_from (State state) const
Gets shortest words for the given state.
Parameters
[in] state State to map shortest words for.
Returns
Set of shortest words.
insert_initial_lengths()
void insert_initial_lengths () private
Inserts initial lengths into the shortest words map.
Inserts initial length of length 0 for final state in the automaton (initial states in the reversed automaton).
Referenced by ShortestWordsMap::ShortestWordsMap().
map_default_shortest_words()
LengthWordsPair map_default_shortest_words (const State state) inline private
Creates default shortest words mapping for yet unprocessed state.
Parameters
[in] state State to map default shortest words.
Returns
Created default shortest words map element for the given state.
Definition at line 86 of file strings.hh.
update_current_words()
static void update_current_words (LengthWordsPair & act, const LengthWordsPair & dst, Symbol symbol) static private
Update words for the current state.
Parameters
[out] act Current state shortest words and length.
[in] dst Transition target state shortest words and length.
[in] symbol Symbol to update with.
Member Data Documentation
fifo_queue
std::deque<State> fifo_queue {} private
FIFO queue for states to process.
Definition at line 60 of file strings.hh.
processed
std::set<State> processed {} private
Set of already processed states.
Definition at line 59 of file strings.hh.
reversed_automaton
const Nfa reversed_automaton private
Reversed input automaton.
Definition at line 61 of file strings.hh.
shortest_words_map
std::unordered_map<State, LengthWordsPair> shortest_words_map {} private
Map mapping states to the shortest words accepted by the automaton from the mapped state.
Definition at line 58 of file strings.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/applications/strings.hh