Mata: SparseSet< Number > Class Template Reference
SparseSet< Number > Class Template Reference
Implementation of a set of non-negative numbers using sparse-set.
#include <sparse-set.hh>
Public Types
using iterator = typename std::vector< Number >::const_iterator
using const_iterator = typename std::vector< Number >::const_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
size_t domain_size () const
bool empty () const
void clear ()
void reserve (size_t u)
bool contains (const Number val) const
void insert (const Number val)
void erase_nocheck (const Number number)
Erase number from the set without checking for its existence.
void erase (const Number val)
SparseSet ()=default
New Mata code.
SparseSet (Number domain_size)
Basic constructor where you may reserve a domain size.
SparseSet (std::initializer_list< Number > list)
template<class InputIterator >
SparseSet (InputIterator first, InputIterator last)
template<class T >
SparseSet (T &container)
SparseSet (const BoolVector &bv)
SparseSet (const SparseSet< Number > &rhs)=default
SparseSet (SparseSet< Number > &&other) noexcept
SparseSet< Number > & operator= (const SparseSet< Number > &rhs)=default
SparseSet< Number > & operator= (SparseSet< Number > &&other) noexcept
bool operator== (const SparseSet< Number > &) const =default
bool consistent ()
bool operator[] (Number q) const
template<class InputIterator >
void insert (InputIterator first, InputIterator last)
template<Iterable T>
void insert (const T &set)
void insert (const std::initializer_list< Number > &list)
template<class InputIterator >
void erase (InputIterator first, InputIterator last)
template<Iterable T>
void erase (const T &set)
void erase (const std::initializer_list< Number > &list)
template<class T >
bool intersects_with (const T &set) const
void complement (Number new_domain_size)
template<typename F >
void filter (F &&is_staying)
void sort ()
template<typename F >
void rename (F &&renaming)
Number max ()
Maximal Number in set.
void truncate ()
Private Attributes
std::vector< Number > dense {}
std::vector< Number > sparse {}
size_t size_ = 0
Number of elements which are in the set (current size).
size_t domain_size_ = 0
Over-approximation of Number in sparse set. It represents the Numbers which were in the set throughout the life of the set until now.
Friends
bool are_disjoint (const SparseSet &A, const SparseSet &B)
Detailed Description
template<typename Number>
class mata::utils::SparseSet< Number >
Implementation of a set of non-negative numbers using sparse-set.
This class implements the interface of a set (similar to std::set) using sparse-set date structure, that is, a pair of vectors dense and sparse (... google it). Importantly
Insertion and removal are constant time.
Iteration is linear in the number of stored elements.
It takes a lot of space, the sparse and dense vectors allocate as many indexes as the maximal stored number.
Template Parameters
Number Number type: type of numbers contained in the container.
Definition at line 48 of file sparse-set.hh.
Member Typedef Documentation
const_iterator
template<typename Number > using const_iterator = typename std::vector<Number>::const_iterator
Definition at line 68 of file sparse-set.hh.
iterator
template<typename Number > using iterator = typename std::vector<Number>::const_iterator
Definition at line 67 of file sparse-set.hh.
Constructor & Destructor Documentation
SparseSet() [1/8]
template<typename Number > SparseSet () default
New Mata code.
SparseSet() [2/8]
template<typename Number > SparseSet (Number domain_size) inline explicit
Basic constructor where you may reserve a domain size.
Definition at line 138 of file sparse-set.hh.
SparseSet() [3/8]
template<typename Number > SparseSet (std::initializer_list< Number > list) inline
Definition at line 142 of file sparse-set.hh.
SparseSet() [4/8]
template<typename Number > template<class InputIterator > SparseSet (InputIterator first, InputIterator last) inline explicit
Definition at line 148 of file sparse-set.hh.
SparseSet() [5/8]
template<typename Number > template<class T > SparseSet (T & container) inline explicit
Definition at line 154 of file sparse-set.hh.
SparseSet() [6/8]
template<typename Number > SparseSet (const BoolVector & bv) inline explicit
Definition at line 161 of file sparse-set.hh.
SparseSet() [7/8]
template<typename Number > SparseSet (const SparseSet< Number > & rhs) default
SparseSet() [8/8]
template<typename Number > SparseSet (SparseSet< Number > && other) inline noexcept
Definition at line 171 of file sparse-set.hh.
References SparseSet< Number >::SparseSet().
Referenced by SparseSet< Number >::SparseSet().
Member Function Documentation
begin() [1/2]
template<typename Number > iterator begin () inline
Definition at line 70 of file sparse-set.hh.
begin() [2/2]
template<typename Number > const_iterator begin () const inline
Definition at line 72 of file sparse-set.hh.
clear()
template<typename Number > void clear () inline
Definition at line 83 of file sparse-set.hh.
complement()
template<typename Number > void complement (Number new_domain_size) inline
Definition at line 260 of file sparse-set.hh.
References SparseSet< Number >::contains(), and SparseSet< Number >::erase_nocheck().
consistent()
template<typename Number > bool consistent () inline
Definition at line 200 of file sparse-set.hh.
contains()
template<typename Number > bool contains (const Number val) const inline
Definition at line 96 of file sparse-set.hh.
Referenced by SparseSet< Number >::complement(), SparseSet< Number >::erase(), SparseSet< Number >::insert(), SparseSet< Number >::intersects_with(), and SparseSet< Number >::operator[]().
domain_size()
template<typename Number > size_t domain_size () const inline
Definition at line 79 of file sparse-set.hh.
empty()
template<typename Number > bool empty () const inline
Definition at line 81 of file sparse-set.hh.
end() [1/2]
template<typename Number > iterator end () inline
Definition at line 74 of file sparse-set.hh.
end() [2/2]
template<typename Number > const_iterator end () const inline
Definition at line 76 of file sparse-set.hh.
erase() [1/4]
template<typename Number > void erase (const Number val) inline
Definition at line 128 of file sparse-set.hh.
References SparseSet< Number >::contains(), and SparseSet< Number >::erase_nocheck().
erase() [2/4]
template<typename Number > void erase (const std::initializer_list< Number > & list) inline
Definition at line 245 of file sparse-set.hh.
erase() [3/4]
template<typename Number > template<Iterable T> void erase (const T & set) inline
Definition at line 243 of file sparse-set.hh.
erase() [4/4]
template<typename Number > template<class InputIterator > void erase (InputIterator first, InputIterator last) inline
Definition at line 234 of file sparse-set.hh.
erase_nocheck()
template<typename Number > void erase_nocheck (const Number number) inline
Erase number from the set without checking for its existence.
Parameters
number Number to be erased.
Precondition
number exists in the set.
Definition at line 122 of file sparse-set.hh.
Referenced by SparseSet< Number >::complement(), and SparseSet< Number >::erase().
filter()
template<typename Number > template<typename F > void filter (F && is_staying) inline
Definition at line 276 of file sparse-set.hh.
insert() [1/4]
template<typename Number > void insert (const Number val) inline
Definition at line 102 of file sparse-set.hh.
References SparseSet< Number >::contains().
insert() [2/4]
template<typename Number > void insert (const std::initializer_list< Number > & list) inline
Definition at line 229 of file sparse-set.hh.
insert() [3/4]
template<typename Number > template<Iterable T> void insert (const T & set) inline
Definition at line 225 of file sparse-set.hh.
insert() [4/4]
template<typename Number > template<class InputIterator > void insert (InputIterator first, InputIterator last) inline
Definition at line 216 of file sparse-set.hh.
intersects_with()
template<typename Number > template<class T > bool intersects_with (const T & set) const inline
Definition at line 249 of file sparse-set.hh.
References SparseSet< Number >::contains().
max()
template<typename Number > Number max () inline
Maximal Number in set.
Expensive operation as it has to compute the maximal Number in linear time.
Definition at line 312 of file sparse-set.hh.
operator=() [1/2]
template<typename Number > SparseSet< Number > & operator= (const SparseSet< Number > & rhs) default
operator=() [2/2]
template<typename Number > SparseSet< Number > & operator= (SparseSet< Number > && other) inline noexcept
Definition at line 180 of file sparse-set.hh.
operator==()
template<typename Number > bool operator== (const SparseSet< Number > &) const default
operator[]()
template<typename Number > bool operator[] (Number q) const inline
Returns
True if predicate for q is set. False otherwise (even if q is out of range of the predicate).
Definition at line 211 of file sparse-set.hh.
References SparseSet< Number >::contains().
rename()
template<typename Number > template<typename F > void rename (F && renaming) inline
Definition at line 296 of file sparse-set.hh.
reserve()
template<typename Number > void reserve (size_t u) inline
Definition at line 87 of file sparse-set.hh.
size()
template<typename Number > size_t size () const inline
Definition at line 78 of file sparse-set.hh.
sort()
template<typename Number > void sort () inline
Definition at line 286 of file sparse-set.hh.
truncate()
template<typename Number > void truncate () inline
Definition at line 321 of file sparse-set.hh.
Friends And Related Symbol Documentation
are_disjoint
template<typename Number > bool are_disjoint (const SparseSet< Number > & A, const SparseSet< Number > & B) friend
Definition at line 331 of file sparse-set.hh.
Member Data Documentation
dense
template<typename Number > std::vector<Number> dense {} private
Definition at line 52 of file sparse-set.hh.
domain_size_
template<typename Number > size_t domain_size_ = 0 private
Over-approximation of Number in sparse set. It represents the Numbers which were in the set throughout the life of the set until now.
truncate() will update the domain size to the current maximal Number + 1. Constructor can preallocate the sparse set and set domain size to the requested value. The structures are preallocated to at least domain_size_ size (can be more when maximal Number is removed).
Definition at line 64 of file sparse-set.hh.
size_
template<typename Number > size_t size_ = 0 private
Number of elements which are in the set (current size).
Definition at line 56 of file sparse-set.hh.
sparse
template<typename Number > std::vector<Number> sparse {} private
Definition at line 53 of file sparse-set.hh.
The documentation for this class was generated from the following file:
/home/misa/Dokumenty/Nfa/mata/include/mata/utils/sparse-set.hh