Mata: mata::nft::plumbing Namespace Reference
mata::nft::plumbing Namespace Reference
Simplified NFA API, used in binding to call NFA algorithms.
Functions
void get_elements (StateSet *element_set, const BoolVector &bool_vec)
void complement (Nft *result, const Nft &aut, const Alphabet &alphabet, const ParameterMap &params={{ "algorithm", "classical"}, { "minimize", "false"}})
void minimize (Nft *res, const Nft &aut)
void determinize (Nft *result, const Nft &aut, std::unordered_map< StateSet, State > *subset_map=nullptr)
void reduce (Nft *result, const Nft &aut, StateRenaming *state_renaming=nullptr, const ParameterMap &params={{ "algorithm", "simulation"}})
void revert (Nft *result, const Nft &aut)
void remove_epsilon (Nft *result, const Nft &aut, Symbol epsilon=EPSILON)
template<class ParsedObject >
void construct (Nft *result, const ParsedObject &parsed, Alphabet *alphabet=nullptr, NameStateMap *state_map=nullptr)
Loads an automaton from Parsed object.
void union_nondet (Nft *unionAutomaton, const Nft &lhs, const Nft &rhs)
void intersection (Nft *res, const Nft &lhs, const Nft &rhs, std::unordered_map< std::pair< State, State >, State > *prod_map=nullptr, const JumpMode jump_mode=JumpMode::RepeatSymbol, const State lhs_first_aux_state=Limits::max_state, const State rhs_first_aux_state=Limits::max_state)
Compute intersection of two NFTs.
void concatenate (Nft *res, const Nft &lhs, const Nft &rhs, bool use_epsilon=false, StateRenaming *lhs_result_state_renaming=nullptr, StateRenaming *rhs_result_state_renaming=nullptr)
Concatenate two NFAs.
Detailed Description
Simplified NFA API, used in binding to call NFA algorithms.
In particular, this mostly includes operations and checks, that do not return Automaton, but instead take resulting automaton as pointer (e.g. void f(Nft* result, const Nft& lhs, const Nft& rhs)).
Function Documentation
complement()
void complement (Nft * result, const Nft & aut, const Alphabet & alphabet, const ParameterMap & params = {{ "algorithm", "classical"}, { "minimize", "false"}}) inline
Definition at line 33 of file plumbing.hh.
concatenate()
void concatenate (Nft * res, const Nft & lhs, const Nft & rhs, bool use_epsilon = false, StateRenaming * lhs_result_state_renaming = nullptr, StateRenaming * rhs_result_state_renaming = nullptr) inline
Concatenate two NFAs.
Parameters
[out] lhs_result_state_renaming Map mapping lhs states to result states.
[out] rhs_result_state_renaming Map mapping rhs states to result states.
Definition at line 95 of file plumbing.hh.
construct()
template<class ParsedObject > void construct (Nft * result, const ParsedObject & parsed, Alphabet * alphabet = nullptr, NameStateMap * state_map = nullptr)
Loads an automaton from Parsed object.
Definition at line 58 of file plumbing.hh.
References OnTheFlyAlphabet::OnTheFlyAlphabet().
determinize()
void determinize (Nft * result, const Nft & aut, std::unordered_map< StateSet, State > * subset_map = nullptr) inline
Definition at line 43 of file plumbing.hh.
get_elements()
void get_elements (StateSet * element_set, const BoolVector & bool_vec) inline
Definition at line 23 of file plumbing.hh.
intersection()
void intersection (Nft * res, const Nft & lhs, const Nft & rhs, std::unordered_map< std::pair< State, State >, State > * prod_map = nullptr, const JumpMode jump_mode = JumpMode::RepeatSymbol, const State lhs_first_aux_state = Limits::max_state, const State rhs_first_aux_state = Limits::max_state) inline
Compute intersection of two NFTs.
Both automata can contain ε-transitions. Epsilons will be handled as alphabet symbols.
Transducers must share alphabets. //TODO: this is not implemented yet. Transducers must have equal values of num_of_levels.
Parameters
[in] lhs First NFT to compute intersection for.
[in] rhs Second NFT to compute intersection for.
[out] prod_map Mapping of pairs of the original states (lhs_state, rhs_state) to new product states (not used internally, allocated only when !=nullptr, expensive).
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE
[in] lhs_first_aux_state The first auxiliary state in lhs. Two auxiliary states does not form a product state.
[in] rhs_first_aux_state The first auxiliary state in rhs. Two auxiliary states does not form a product state.
Returns
NFT as a product of NFTs lhs and rhs.
Definition at line 84 of file plumbing.hh.
minimize()
void minimize (Nft * res, const Nft & aut) inline
Definition at line 41 of file plumbing.hh.
References mata::nft::minimize(), and Nft::operator=().
reduce()
void reduce (Nft * result, const Nft & aut, StateRenaming * state_renaming = nullptr, const ParameterMap & params = {{ "algorithm", "simulation"}}) inline
Definition at line 47 of file plumbing.hh.
remove_epsilon()
void remove_epsilon (Nft * result, const Nft & aut, Symbol epsilon = EPSILON) inline
Definition at line 54 of file plumbing.hh.
References Nft::operator=(), and mata::nft::remove_epsilon().
revert()
void revert (Nft * result, const Nft & aut) inline
Definition at line 52 of file plumbing.hh.
References Nft::operator=(), and mata::nft::revert().
union_nondet()
void union_nondet (Nft * unionAutomaton, const Nft & lhs, const Nft & rhs) inline
Definition at line 65 of file plumbing.hh.
References Nft::operator=(), and mata::nft::union_nondet().