Mata: mata::nfa::plumbing Namespace Reference
mata::nfa::plumbing Namespace Reference
Wrappers around various support functions.
Functions
void get_elements (StateSet *element_set, const BoolVector &bool_vec)
void complement (Nfa *result, const Nfa &aut, const Alphabet &alphabet, const ParameterMap &params={{ "algorithm", "classical"}, { "minimize", "false"}})
void minimize (Nfa *res, const Nfa &aut, const ParameterMap &params={{ "algorithm", "brzozowski"}})
void determinize (Nfa *result, const Nfa &aut, std::unordered_map< StateSet, State > *subset_map=nullptr)
void reduce (Nfa *result, const Nfa &aut, StateRenaming *state_renaming=nullptr, const ParameterMap &params={{ "algorithm", "simulation"}})
void revert (Nfa *result, const Nfa &aut)
void remove_epsilon (Nfa *result, const Nfa &aut, Symbol epsilon=EPSILON)
template<class ParsedObject >
void construct (Nfa *result, const ParsedObject &parsed, Alphabet *alphabet=nullptr, NameStateMap *state_map=nullptr)
Loads an automaton from Parsed object.
void union_nondet (Nfa *unionAutomaton, const Nfa &lhs, const Nfa &rhs)
void intersection (Nfa *res, const Nfa &lhs, const Nfa &rhs, Symbol first_epsilon=EPSILON, std::unordered_map< std::pair< State, State >, State > *prod_map=nullptr)
Compute intersection of two NFAs.
void concatenate (Nfa *res, const Nfa &lhs, const Nfa &rhs, bool use_epsilon=false, StateRenaming *lhs_result_state_renaming=nullptr, StateRenaming *rhs_result_state_renaming=nullptr)
Concatenate two NFAs.
void reduce_residual_with (Nfa *res, const Nfa &nfa)
Reduce NFA using residual construction.
void reduce_residual_after (Nfa *res, const Nfa &nfa)
Reduce NFA using residual construction.
Detailed Description
Wrappers around various support functions.
Function Documentation
complement()
void complement (Nfa * result, const Nfa & aut, const Alphabet & alphabet, const ParameterMap & params = {{ "algorithm", "classical"}, { "minimize", "false"}}) inline
Definition at line 35 of file plumbing.hh.
concatenate()
void concatenate (Nfa * res, const Nfa & lhs, const Nfa & rhs, bool use_epsilon = false, StateRenaming * lhs_result_state_renaming = nullptr, StateRenaming * rhs_result_state_renaming = nullptr) inline
Concatenate two NFAs.
Parameters
[out] lhs_result_state_renaming Map mapping lhs states to result states.
[out] rhs_result_state_renaming Map mapping rhs states to result states.
Definition at line 94 of file plumbing.hh.
construct()
template<class ParsedObject > void construct (Nfa * result, const ParsedObject & parsed, Alphabet * alphabet = nullptr, NameStateMap * state_map = nullptr)
Loads an automaton from Parsed object.
Definition at line 60 of file plumbing.hh.
References OnTheFlyAlphabet::OnTheFlyAlphabet().
determinize()
void determinize (Nfa * result, const Nfa & aut, std::unordered_map< StateSet, State > * subset_map = nullptr) inline
Definition at line 45 of file plumbing.hh.
get_elements()
void get_elements (StateSet * element_set, const BoolVector & bool_vec) inline
Definition at line 25 of file plumbing.hh.
intersection()
void intersection (Nfa * res, const Nfa & lhs, const Nfa & rhs, Symbol first_epsilon = EPSILON, std::unordered_map< std::pair< State, State >, State > * prod_map = nullptr) inline
Compute intersection of two NFAs.
Both automata can contain ε-transitions. The product preserves the ε-transitions, i.e., for each each product state (s, t) withs -ε-> p, (s, t) -ε-> (p, t) is created, and vice versa.
Automata must share alphabets.
Parameters
[out] res The resulting intersection NFA.
[in] lhs Input NFA.
[in] rhs Input NFA.
[in] first_epsilon smallest epsilon.
[out] prod_map Mapping of pairs of the original states (lhs_state, rhs_state) to new product states (not used internally, allocated only when !=nullptr, expensive).
Returns
NFA as a product of NFAs lhs and rhs with ε-transitions preserved.
Definition at line 84 of file plumbing.hh.
minimize()
void minimize (Nfa * res, const Nfa & aut, const ParameterMap & params = {{ "algorithm", "brzozowski"}}) inline
Definition at line 43 of file plumbing.hh.
reduce()
void reduce (Nfa * result, const Nfa & aut, StateRenaming * state_renaming = nullptr, const ParameterMap & params = {{ "algorithm", "simulation"}}) inline
Definition at line 49 of file plumbing.hh.
reduce_residual_after()
void reduce_residual_after (Nfa * res, const Nfa & nfa) inline
Reduce NFA using residual construction.
The residual construction of the residual automaton and the removal of the covering states is done after the final determinization.
Similar performance to reduce_residual_with(). The output is almost the same except the transitions: transitions may slightly differ, but the number of states is the same for both algorithm types.
Definition at line 125 of file plumbing.hh.
References Nfa::operator=(), and mata::nfa::algorithms::reduce_residual_after().
reduce_residual_with()
void reduce_residual_with (Nfa * res, const Nfa & nfa) inline
Reduce NFA using residual construction.
The residual construction of the residual automaton and the removal of the covering states is done during the last determinization.
Similar performance to reduce_residual_after(). The output is almost the same except the transitions: transitions may slightly differ, but the number of states is the same for both algorithm types.
Definition at line 110 of file plumbing.hh.
References Nfa::operator=(), and mata::nfa::algorithms::reduce_residual_with().
remove_epsilon()
void remove_epsilon (Nfa * result, const Nfa & aut, Symbol epsilon = EPSILON) inline
Definition at line 56 of file plumbing.hh.
References Nfa::operator=(), and mata::nfa::remove_epsilon().
revert()
void revert (Nfa * result, const Nfa & aut) inline
Definition at line 54 of file plumbing.hh.
References Nfa::operator=(), and mata::nfa::revert().
union_nondet()
void union_nondet (Nfa * unionAutomaton, const Nfa & lhs, const Nfa & rhs) inline
Definition at line 67 of file plumbing.hh.
References Nfa::operator=(), and mata::nfa::union_nondet().