Mata: mata::nfa Namespace Reference
mata::nfa Namespace Reference
Namespaces
namespace algorithms
Concrete NFA implementations of algorithms, such as complement, inclusion, or universality checking.
namespace builder
Namespace providing options to build NFAs.
namespace plumbing
Wrappers around various support functions.
Classes
struct bool_pack
Pack of bools for reasoning about a sequence of parameters.
class Delta
Delta is a data structure for representing transition relation.
struct Limits
class Move
Move from a StatePost for a single source state, represented as a pair of symbol and target state target.
class Nfa
A class representing an NFA.
struct Run
class StatePost
A data structure representing possible transitions over different symbols from a source state.
class SymbolPost
Structure represents a post of a single symbol: a set of target states in transitions.
class SynchronizedExistentialSymbolPostIterator
Specialization of utils::SynchronizedExistentialIterator for iterating over SymbolPosts.
struct Transition
A single transition in Delta represented as a triple(source, symbol, target).
Typedefs
template<typename... Ts>
using conjunction = std::is_same< bool_pack< true, Ts::value... >, bool_pack< Ts::value..., true > >
Check that for all values in a pack Ts are 'true'.
template<typename T , typename... Ts>
using AreAllOfType = typename conjunction< std::is_same< Ts, T >... >::type
Check that all types in a sequence of parameters Ts are of type T.
using State = unsigned long
using StateSet = mata::utils::OrdVector< State >
using StateRenaming = std::unordered_map< State, State >
using ParameterMap = std::unordered_map< std::string, std::string >
Map of additional parameter name and value pairs.
Enumerations
enum class EpsilonClosureOpt : unsigned {
NONE = 1 << 0 ,
BEFORE = 1 << 1 ,
AFTER = 1 << 2 ,
BEFORE_AND_AFTER = BEFORE | AFTER
}
enum class ProductFinalStateCondition {
AND ,
OR
}
Functions
template<typename... Nfas, typename = AreAllOfType<const Nfa&, Nfas...>>
OnTheFlyAlphabet create_alphabet (const Nfas &... nfas)
Create alphabet from variadic number of NFAs given as arguments.
OnTheFlyAlphabet create_alphabet (const std::vector< std::reference_wrapper< const Nfa > > &nfas)
Create alphabet from a vector of NFAs.
OnTheFlyAlphabet create_alphabet (const std::vector< std::reference_wrapper< Nfa > > &nfas)
Create alphabet from a vector of NFAs.
OnTheFlyAlphabet create_alphabet (const std::vector< Nfa * > &nfas)
Create alphabet from a vector of NFAs.
OnTheFlyAlphabet create_alphabet (const std::vector< const Nfa * > &nfas)
Create alphabet from a vector of NFAs.
Nfa union_nondet (const Nfa &lhs, const Nfa &rhs)
Compute non-deterministic union.
Nfa union_det_complete (const Nfa &lhs, const Nfa &rhs)
Compute union of two complete deterministic NFAs.
Nfa product (const Nfa &lhs, const Nfa &rhs, ProductFinalStateCondition final_condition=ProductFinalStateCondition::AND, Symbol first_epsilon=EPSILON, std::unordered_map< std::pair< State, State >, State > *prod_map=nullptr)
Compute product of two NFAs with OR condition on the final states.
Nfa lang_difference (const Nfa &nfa_included, const Nfa &nfa_excluded, std::optional< std::function< bool(const Nfa &, const Nfa &, const StateSet &, const StateSet &, const State, const Nfa &)> > macrostate_discover=std::nullopt)
Compute a language difference as nfa_included \ nfa_excluded.
Nfa intersection (const Nfa &lhs, const Nfa &rhs, const Symbol first_epsilon=EPSILON, std::unordered_map< std::pair< State, State >, State > *prod_map=nullptr)
Compute intersection of two NFAs.
Nfa concatenate (const Nfa &lhs, const Nfa &rhs, bool use_epsilon=false, StateRenaming *lhs_state_renaming=nullptr, StateRenaming *rhs_state_renaming=nullptr)
Concatenate two NFAs.
Nfa complement (const Nfa &aut, const Alphabet &alphabet, const ParameterMap &params={ { "algorithm", "classical" } })
Compute automaton accepting complement of aut.
Nfa complement (const Nfa &aut, const utils::OrdVector< Symbol > &symbols, const ParameterMap &params={ { "algorithm", "classical" } })
Compute automaton accepting complement of aut.
Nfa minimize (const Nfa &aut, const ParameterMap &params={ { "algorithm", "brzozowski" } })
Compute minimal deterministic automaton.
Nfa determinize (const Nfa &aut, std::unordered_map< StateSet, State > *subset_map=nullptr, std::optional< std::function< bool(const Nfa &, const State, const StateSet &)> > macrostate_discover=std::nullopt)
Determinize automaton.
Nfa reduce (const Nfa &aut, StateRenaming *state_renaming=nullptr, const ParameterMap &params={{ "algorithm", "simulation" }, { "type", "after" }, { "direction", "forward" } })
Reduce the size of the automaton.
bool is_included (const Nfa &smaller, const Nfa &bigger, Run *cex, const Alphabet *alphabet=nullptr, const ParameterMap &params={{ "algorithm", "antichains" }})
Checks inclusion of languages of two NFAs: smaller and bigger (smaller <= bigger).
bool is_included (const Nfa &smaller, const Nfa &bigger, const Alphabet *const alphabet=nullptr, const ParameterMap &params={{ "algorithm", "antichains" }})
Checks inclusion of languages of two NFAs: smaller and bigger (smaller <= bigger).
bool are_equivalent (const Nfa &lhs, const Nfa &rhs, const Alphabet *alphabet, const ParameterMap &params={{ "algorithm", "antichains"}})
Perform equivalence check of two NFAs: lhs and rhs.
bool are_equivalent (const Nfa &lhs, const Nfa &rhs, const ParameterMap &params={{ "algorithm", "antichains"}})
Perform equivalence check of two NFAs: lhs and rhs.
Nfa revert (const Nfa &aut)
Nfa fragile_revert (const Nfa &aut)
Nfa simple_revert (const Nfa &aut)
Nfa somewhat_simple_revert (const Nfa &aut)
Nfa remove_epsilon (const Nfa &aut, Symbol epsilon=EPSILON)
Run encode_word (const Alphabet *alphabet, const std::vector< std::string > &input)
Encodes a vector of strings (each corresponding to one symbol) into a Word instance.
utils::OrdVector< Symbol > get_symbols_to_work_with (const nfa::Nfa &nfa, const Alphabet *const shared_alphabet=nullptr)
Get the set of symbols to work with during operations.
std::optional< Word > get_word_from_lang_difference (const Nfa &nfa_included, const Nfa &nfa_excluded)
Get any arbitrary accepted word in the language difference of nfa_included without nfa_excluded.
Variables
const std::string TYPE_NFA
constexpr Symbol EPSILON = Limits::max_symbol
A non-deterministic finite automaton.
Typedef Documentation
AreAllOfType
template<typename T , typename... Ts> using AreAllOfType = typename conjunction<std::is_same<Ts, T>...>::type
Check that all types in a sequence of parameters Ts are of type T.
Definition at line 663 of file nfa.hh.
conjunction
template<typename... Ts> using conjunction = std::is_same<bool_pack<true,Ts::value...>, bool_pack<Ts::value..., true> >
Check that for all values in a pack Ts are 'true'.
Definition at line 661 of file nfa.hh.
ParameterMap
using ParameterMap = std::unordered_map<std::string, std::string>
Map of additional parameter name and value pairs.
Used by certain functions for specifying some additional parameters in the following format:
ParameterMap {
    { "algorithm", "classical" },
    { "minimize", "true" }
}
Definition at line 50 of file types.hh.
State
using State = unsigned long
Definition at line 17 of file types.hh.
StateRenaming
using StateRenaming = std::unordered_map<State, State>
Definition at line 37 of file types.hh.
StateSet
using StateSet = mata::utils::OrdVector<State>
Definition at line 18 of file types.hh.
Enumeration Type Documentation
EpsilonClosureOpt
enum class EpsilonClosureOpt : unsigned strong
Enumerator
NONE
No epsilon closure.
BEFORE
Epsilon closure before the transition.
AFTER
Epsilon closure after the transition.
BEFORE_AND_AFTER
Epsilon closure before and after the transition.
Definition at line 25 of file types.hh.
ProductFinalStateCondition
enum class ProductFinalStateCondition strong
Enumerator
AND
Both original states have to be final.
OR
At least one of the original states has to be final.
Definition at line 32 of file types.hh.
Function Documentation
are_equivalent() [1/2]
bool are_equivalent (const Nfa & lhs, const Nfa & rhs, const Alphabet * alphabet, const ParameterMap & params = {{ "algorithm", "antichains"}})
Perform equivalence check of two NFAs: lhs and rhs.
Parameters
[in] lhs First automaton to concatenate.
[in] rhs Second automaton to concatenate.
[in] alphabet Alphabet of both NFAs to compute with.
[in] params[ Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if lhs and rhs are equivalent, false otherwise.
are_equivalent() [2/2]
bool are_equivalent (const Nfa & lhs, const Nfa & rhs, const ParameterMap & params = {{ "algorithm", "antichains"}})
Perform equivalence check of two NFAs: lhs and rhs.
The current implementation of Nfa does not accept input alphabet. For this reason, an alphabet has to be created from all transitions each time an operation on alphabet is called. When calling this function, the alphabet has to be computed first.
Hence, this function is less efficient than its alternative taking already defined alphabet as its parameter. That way, alphabet has to be computed only once, as opposed to the current ad-hoc construction of the alphabet. The use of the alternative with defined alphabet should be preferred.
Parameters
[in] lhs First automaton to concatenate.
[in] rhs Second automaton to concatenate.
[in] params Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if lhs and rhs are equivalent, false otherwise.
complement() [1/2]
Nfa complement (const Nfa & aut, const Alphabet & alphabet, const ParameterMap & params = { { "algorithm", "classical" } })
Compute automaton accepting complement of aut.
Parameters
[in] aut Automaton whose complement to compute.
[in] alphabet Alphabet used for complementation.
[in] params Optional parameters to control the complementation algorithm:
"algorithm":
"classical": The classical algorithm determinizes the automaton, makes it complete, and swaps final and non-final states.
"brzozowski": The Brzozowski algorithm determinizes the automaton using Brzozowski minimization, makes it complete, and swaps final and non-final states.
Returns
Complemented automaton.
complement() [2/2]
Nfa complement (const Nfa & aut, const utils::OrdVector< Symbol > & symbols, const ParameterMap & params = { { "algorithm", "classical" } })
Compute automaton accepting complement of aut.
This overloaded version complements over an already created ordered set of symbols instead of an alphabet. This is a more efficient solution in case you already have symbols precomputed or want to complement multiple automata over the same set of symbols: the function does not need to compute the ordered set of symbols from the alphabet again (and for each automaton).
Parameters
[in] aut Automaton whose complement to compute.
[in] symbols Symbols to complement over.
[in] params Optional parameters to control the complementation algorithm:
"algorithm":
"classical": The classical algorithm determinizes the automaton, makes it complete, and swaps final and non-final states.
"brzozowski": The Brzozowski algorithm determinizes the automaton using Brzozowski minimization, makes it complete, and swaps final and non-final states.
Returns
Complemented automaton.
concatenate()
Nfa concatenate (const Nfa & lhs, const Nfa & rhs, bool use_epsilon = false, StateRenaming * lhs_state_renaming = nullptr, StateRenaming * rhs_state_renaming = nullptr)
Concatenate two NFAs.
Supports epsilon symbols when use_epsilon is set to true.
Parameters
[in] lhs First automaton to concatenate.
[in] rhs Second automaton to concatenate.
[in] use_epsilon Whether to concatenate over epsilon symbol.
[out] lhs_state_renaming Map mapping lhs states to result states.
[out] rhs_state_renaming Map mapping rhs states to result states.
Returns
Concatenated automaton.
create_alphabet() [1/5]
template<typename... Nfas, typename = AreAllOfType<const Nfa&, Nfas...>> OnTheFlyAlphabet create_alphabet (const Nfas &... nfas) inline
Create alphabet from variadic number of NFAs given as arguments.
Template Parameters
in] Nfas Type Nfa.
Parameters
[in] nfas NFAs to create alphabet from.
Returns
Created alphabet.
Definition at line 672 of file nfa.hh.
References Nfa::fill_alphabet(), and OnTheFlyAlphabet::OnTheFlyAlphabet().
create_alphabet() [2/5]
OnTheFlyAlphabet create_alphabet (const std::vector< const Nfa * > & nfas)
Create alphabet from a vector of NFAs.
Parameters
[in] nfas Vector of pointers to NFAs to create alphabet from.
Returns
Created alphabet.
create_alphabet() [3/5]
OnTheFlyAlphabet create_alphabet (const std::vector< Nfa * > & nfas)
Create alphabet from a vector of NFAs.
Parameters
[in] nfas Vector of pointers to NFAs to create alphabet from.
Returns
Created alphabet.
create_alphabet() [4/5]
OnTheFlyAlphabet create_alphabet (const std::vector< std::reference_wrapper< const Nfa > > & nfas)
Create alphabet from a vector of NFAs.
Parameters
[in] nfas Vector of NFAs to create alphabet from.
Returns
Created alphabet.
create_alphabet() [5/5]
OnTheFlyAlphabet create_alphabet (const std::vector< std::reference_wrapper< Nfa > > & nfas)
Create alphabet from a vector of NFAs.
Parameters
[in] nfas Vector of NFAs to create alphabet from.
Returns
Created alphabet.
determinize()
Nfa determinize (const Nfa & aut, std::unordered_map< StateSet, State > * subset_map = nullptr, std::optional< std::function< bool(const Nfa &, const State, const StateSet &)> > macrostate_discover = std::nullopt)
Determinize automaton.
Parameters
[in] aut Automaton to determinize.
[out] subset_map Map that maps sets of states of input automaton to states of determinized automaton.
[in] macrostate_discover Callback event handler for discovering a new macrostate for the first time. The parameters are the determinized NFA constructed so far, the current macrostate, and the set of the original states corresponding to the macrostate. Return true if the determinization should continue, and false if the determinization should stop and return only the determinized NFA constructed so far.
Returns
Determinized automaton.
Todo:
: TODO: Add support for specifying first epsilon symbol and compute epsilon closure during determinization.
encode_word()
Run encode_word (const Alphabet * alphabet, const std::vector< std::string > & input)
Encodes a vector of strings (each corresponding to one symbol) into a Word instance.
fragile_revert()
Nfa fragile_revert (const Nfa & aut)
get_symbols_to_work_with()
utils::OrdVector< Symbol > get_symbols_to_work_with (const nfa::Nfa & nfa, const Alphabet *const shared_alphabet = nullptr)
Get the set of symbols to work with during operations.
Parameters
[in] shared_alphabet Optional alphabet shared between NFAs passed as an argument to a function.
get_word_from_lang_difference()
std::optional< Word > get_word_from_lang_difference (const Nfa & nfa_included, const Nfa & nfa_excluded)
Get any arbitrary accepted word in the language difference of nfa_included without nfa_excluded.
The language difference automaton is lazily constructed without computing the whole determinized automata and the complememt of nfa_excluded. The algorithm returns an arbitrary word from the language difference constructed until the first macrostate with a final state in the original states in nfa_included and without any corresponding final states in nfa_excluded is encountered.
Precondition
The automaton does not contain any epsilon transitions.
Parameters
[in] nfa_included NFA to include in the language difference.
[in] nfa_excluded NFA to exclude in the language difference. TODO: Support lazy epsilon closure?
Returns
An arbitrary word from the language difference, or std::nullopt if the language difference automaton is universal on the set of symbols from transitions of nfa_included.
intersection()
Nfa intersection (const Nfa & lhs, const Nfa & rhs, const Symbol first_epsilon = EPSILON, std::unordered_map< std::pair< State, State >, State > * prod_map = nullptr)
Compute intersection of two NFAs.
Both automata can contain ε-transitions. The product preserves the ε-transitions, i.e., for each each product state (s, t) withs -ε-> p, (s, t) -ε-> (p, t) is created, and vice versa.
Automata must share alphabets. //TODO: this is not implemented yet.
Parameters
[in] lhs First NFA to compute intersection for.
[in] rhs Second NFA to compute intersection for.
[in] first_epsilon smallest epsilon. //TODO: this should eventually be taken from the alphabet as anything larger than the largest symbol?
[out] prod_map Mapping of pairs of the original states (lhs_state, rhs_state) to new product states (not used internally, allocated only when !=nullptr, expensive).
Returns
NFA as a product of NFAs lhs and rhs with ε-transitions preserved.
is_included() [1/2]
bool is_included (const Nfa & smaller, const Nfa & bigger, const Alphabet *const alphabet = nullptr, const ParameterMap & params = {{ "algorithm", "antichains" }}) inline
Checks inclusion of languages of two NFAs: smaller and bigger (smaller <= bigger).
Parameters
[in] smaller First automaton to concatenate.
[in] bigger Second automaton to concatenate.
[in] alphabet Alphabet of both NFAs to compute with.
[in] params Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if smaller is included in bigger, false otherwise.
Definition at line 901 of file nfa.hh.
is_included() [2/2]
bool is_included (const Nfa & smaller, const Nfa & bigger, Run * cex, const Alphabet * alphabet = nullptr, const ParameterMap & params = {{ "algorithm", "antichains" }})
Checks inclusion of languages of two NFAs: smaller and bigger (smaller <= bigger).
Parameters
[in] smaller First automaton to concatenate.
[in] bigger Second automaton to concatenate.
[out] cex Counterexample for the inclusion.
[in] alphabet Alphabet of both NFAs to compute with.
[in] params Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if smaller is included in bigger, false otherwise.
lang_difference()
Nfa lang_difference (const Nfa & nfa_included, const Nfa & nfa_excluded, std::optional< std::function< bool(const Nfa &, const Nfa &, const StateSet &, const StateSet &, const State, const Nfa &)> > macrostate_discover = std::nullopt)
Compute a language difference as nfa_included \ nfa_excluded.
Computed as a lazy intersection of nfa_included and a complement of nfa_excluded. The NFAs are lazily determinized and the complement is constructed lazily as well, guided by nfa_included.
Parameters
[in] nfa_included NFA to include in the difference.
[in] nfa_excluded NFA to exclude from the difference.
[in] macrostate_discover Callback event handler for discovering a new macrostate in the language difference automaton for the first time. Return true if the computation should continue, and false if the computation should stop and return only the NFA for the language difference constructed so far. The parameters are: const Nfa& nfa_included, const Nfa& nfa_excluded, const StateSet& macrostate_included_state_set, const StateSet& macrostate_excluded_state_set, const State macrostate, const Nfa& nfa_lang_difference.
Todo:
: TODO: Add support for specifying first epsilon symbol and compute epsilon closure during determinization.
minimize()
Nfa minimize (const Nfa & aut, const ParameterMap & params = { { "algorithm", "brzozowski" } })
Compute minimal deterministic automaton.
Parameters
[in] aut Automaton whose minimal version to compute.
[in] params Optional parameters to control the minimization algorithm:
"algorithm": "brzozowski"
Returns
Minimal deterministic automaton.
product()
Nfa product (const Nfa & lhs, const Nfa & rhs, ProductFinalStateCondition final_condition = ProductFinalStateCondition::AND, Symbol first_epsilon = EPSILON, std::unordered_map< std::pair< State, State >, State > * prod_map = nullptr)
Compute product of two NFAs with OR condition on the final states.
Automata must share alphabets. //TODO: this is not implemented yet.
Parameters
lhs First NFA.
rhs Second NFA.
final_condition Condition for a product state to be final.
AND: both original states have to be final.
OR: at least one of the original states has to be final.
first_epsilon Smallest epsilon symbol. //TODO: this should eventually be taken from the alphabet as anything larger than the largest symbol?
prod_map Mapping of pairs of the original states (lhs_state, rhs_state) to new product states (not used internally, allocated only when !=nullptr, expensive).
reduce()
Nfa reduce (const Nfa & aut, StateRenaming * state_renaming = nullptr, const ParameterMap & params = {{ "algorithm", "simulation" }, { "type", "after" }, { "direction", "forward" } })
Reduce the size of the automaton.
Parameters
[in] aut Automaton to reduce.
[out] state_renaming Mapping of original states to reduced states.
[in] params Optional parameters to control the reduction algorithm:
"algorithm": "simulation", "residual", and options to parametrize residual reduction, not utilized in simulation
"type": "after", "with",
"direction": "forward", "backward".
Returns
Reduced automaton.
remove_epsilon()
Nfa remove_epsilon (const Nfa & aut, Symbol epsilon = EPSILON)
Referenced by mata::nfa::plumbing::remove_epsilon().
revert()
Nfa revert (const Nfa & aut)
Referenced by mata::nfa::plumbing::revert().
simple_revert()
Nfa simple_revert (const Nfa & aut)
somewhat_simple_revert()
Nfa somewhat_simple_revert (const Nfa & aut)
union_det_complete()
Nfa union_det_complete (const Nfa & lhs, const Nfa & rhs)
Compute union of two complete deterministic NFAs.
Perserves determinism.
The union is computed by product construction with OR condition on the final states.
Parameters
lhs First complete deterministic automaton.
rhs Second complete deterministic automaton.
union_nondet()
Nfa union_nondet (const Nfa & lhs, const Nfa & rhs)
Compute non-deterministic union.
Does not add epsilon transitions, just unites initial and final states.
Returns
Non-deterministic union of lhs and rhs.
Referenced by mata::nfa::plumbing::union_nondet().
Variable Documentation
EPSILON
constexpr Symbol EPSILON = Limits::max_symbol constexpr
A non-deterministic finite automaton.
An epsilon symbol which is now defined as the maximal value of data type used for symbols.
Definition at line 63 of file types.hh.
Referenced by Nfa::is_epsilon().
TYPE_NFA
const std::string TYPE_NFA extern