Mata: mata::nft Namespace Reference
mata::nft Namespace Reference
Namespaces
namespace algorithms
Concrete NFT implementations of algorithms, such as complement, inclusion, or universality checking.
namespace builder
Namespace providing options to build NFAs.
namespace plumbing
Simplified NFA API, used in binding to call NFA algorithms.
Classes
struct bool_pack
Pack of bools for reasoning about a sequence of parameters.
class Levels
class Nft
A class representing an NFT.
Typedefs
using Transition = mata::nfa::Transition
using Move = mata::nfa::Move
using SymbolPost = mata::nfa::SymbolPost
using StatePost = mata::nfa::StatePost
using SynchronizedExistentialSymbolPostIterator = mata::nfa::SynchronizedExistentialSymbolPostIterator
using Delta = mata::nfa::Delta
template<typename... Ts>
using conjunction = std::is_same< bool_pack< true, Ts::value... >, bool_pack< Ts::value..., true > >
Check that for all values in a pack Ts are 'true'.
template<typename T , typename... Ts>
using AreAllOfType = typename conjunction< std::is_same< Ts, T >... >::type
Check that all types in a sequence of parameters Ts are of type T.
using Level = unsigned
using State = mata::nfa::State
using StateSet = mata::nfa::StateSet
using Run = mata::nfa::Run
using EpsilonClosureOpt = mata::nfa::EpsilonClosureOpt
using StateRenaming = mata::nfa::StateRenaming
using ParameterMap = mata::nfa::ParameterMap
Map of additional parameter name and value pairs.
using Limits = mata::nfa::Limits
using ProductFinalStateCondition = mata::nfa::ProductFinalStateCondition
Enumerations
enum class JumpMode {
RepeatSymbol ,
AppendDontCares
}
A non-deterministic finite transducer.
Functions
Nft union_nondet (const Nft &lhs, const Nft &rhs)
Compute non-deterministic union.
Nft union_det_complete (const Nft &lhs, const Nft &rhs)=delete
Nft product (const Nft &lhs, const Nft &rhs, ProductFinalStateCondition final_condition, Symbol first_epsilon, std::unordered_map< std::pair< State, State >, State > *prod_map)=delete
Nft intersection (const Nft &lhs, const Nft &rhs, std::unordered_map< std::pair< State, State >, State > *prod_map=nullptr, JumpMode jump_mode=JumpMode::RepeatSymbol, State lhs_first_aux_state=Limits::max_state, State rhs_first_aux_state=Limits::max_state)
Compute intersection of two NFTs.
Nft compose (const Nft &lhs, const Nft &rhs, const utils::OrdVector< Level > &lhs_sync_levels, const utils::OrdVector< Level > &rhs_sync_levels, bool project_out_sync_levels=true, JumpMode jump_mode=JumpMode::RepeatSymbol)
Composes two NFTs (lhs || rhs; read as "rhs after lhs").
Nft compose (const Nft &lhs, const Nft &rhs, Level lhs_sync_level=1, Level rhs_sync_level=0, bool project_out_sync_levels=true, JumpMode jump_mode=JumpMode::RepeatSymbol)
Composes two NFTs (lhs || rhs; read as "rhs after lhs").
Nft concatenate (const Nft &lhs, const Nft &rhs, bool use_epsilon=false, StateRenaming *lhs_state_renaming=nullptr, StateRenaming *rhs_state_renaming=nullptr)
Concatenate two NFTs.
Nft complement (const Nft &aut, const Alphabet &alphabet, const ParameterMap &params={{ "algorithm", "classical" }, { "minimize", "false" }})
Compute automaton accepting complement of aut.
Nft complement (const Nft &aut, const utils::OrdVector< Symbol > &symbols, const ParameterMap &params={{ "algorithm", "classical" }, { "minimize", "false" }})
Compute automaton accepting complement of aut.
Nft minimize (const Nft &aut, const ParameterMap &params={{ "algorithm", "brzozowski" }})
Compute minimal deterministic automaton.
Nft determinize (const Nft &aut, std::unordered_map< StateSet, State > *subset_map=nullptr)
Determinize automaton.
Nft reduce (const Nft &aut, StateRenaming *state_renaming=nullptr, const ParameterMap &params={{ "algorithm", "simulation" } })
Reduce the size of the automaton.
bool is_included (const Nft &smaller, const Nft &bigger, Run *cex, const Alphabet *alphabet=nullptr, JumpMode jump_mode=JumpMode::RepeatSymbol, const ParameterMap &params={{ "algorithm", "antichains" }})
Checks inclusion of languages of two NFTs: smaller and bigger (smaller <= bigger).
bool is_included (const Nft &smaller, const Nft &bigger, const Alphabet *const alphabet=nullptr, JumpMode jump_mode=JumpMode::RepeatSymbol, const ParameterMap &params={{ "algorithm", "antichains" }})
Checks inclusion of languages of two NFTs: smaller and bigger (smaller <= bigger).
bool are_equivalent (const Nft &lhs, const Nft &rhs, const Alphabet *alphabet, JumpMode jump_mode=JumpMode::RepeatSymbol, const ParameterMap &params={{ "algorithm", "antichains"}})
Perform equivalence check of two NFTs: lhs and rhs.
bool are_equivalent (const Nft &lhs, const Nft &rhs, JumpMode JumpMode=JumpMode::RepeatSymbol, const ParameterMap &params={{ "algorithm", "antichains"}})
Perform equivalence check of two NFTs: lhs and rhs.
Nft revert (const Nft &aut)
Nft fragile_revert (const Nft &aut)
Nft simple_revert (const Nft &aut)
Nft somewhat_simple_revert (const Nft &aut)
Nft invert_levels (const Nft &aut, JumpMode jump_mode=JumpMode::RepeatSymbol)
Inverts the levels of the given transducer aut.
Nft remove_epsilon (const Nft &aut, Symbol epsilon=EPSILON)
Remove simple epsilon transitions.
Nft project_out (const Nft &nft, const utils::OrdVector< Level > &levels_to_project, JumpMode jump_mode=JumpMode::RepeatSymbol)
Projects out specified levels levels_to_project in the given transducer nft.
Nft project_out (const Nft &nft, Level level_to_project, JumpMode jump_mode=JumpMode::RepeatSymbol)
Projects out specified level level_to_project in the given transducer nft.
Nft project_to (const Nft &nft, const utils::OrdVector< Level > &levels_to_project, JumpMode jump_mode=JumpMode::RepeatSymbol)
Projects to specified levels levels_to_project in the given transducer nft.
Nft project_to (const Nft &nft, Level level_to_project, JumpMode jump_mode=JumpMode::RepeatSymbol)
Projects to a specified level level_to_project in the given transducer nft.
Nft insert_levels (const Nft &nft, const BoolVector &new_levels_mask, JumpMode jump_mode=JumpMode::RepeatSymbol)
Inserts new levels, as specified by the mask new_levels_mask, into the given transducer nft.
Nft insert_level (const Nft &nft, Level new_level, JumpMode jump_mode=JumpMode::RepeatSymbol)
Inserts a new level new_level into the given transducer nft.
Run encode_word (const Alphabet *alphabet, const std::vector< std::string > &input)
Encodes a vector of strings (each corresponding to one symbol) into a Word instance.
Variables
const std::string TYPE_NFT
constexpr Symbol EPSILON = mata::nfa::EPSILON
An epsilon symbol which is now defined as the maximal value of data type used for symbols.
constexpr Symbol DONT_CARE = EPSILON - 1
constexpr Level DEFAULT_LEVEL { 0 }
constexpr Level DEFAULT_NUM_OF_LEVELS { 2 }
Typedef Documentation
AreAllOfType
template<typename T , typename... Ts> using AreAllOfType = typename conjunction<std::is_same<Ts, T>...>::type
Check that all types in a sequence of parameters Ts are of type T.
Definition at line 759 of file nft.hh.
conjunction
template<typename... Ts> using conjunction = std::is_same<bool_pack<true,Ts::value...>, bool_pack<Ts::value..., true> >
Check that for all values in a pack Ts are 'true'.
Definition at line 757 of file nft.hh.
Delta
using Delta = mata::nfa::Delta
Definition at line 30 of file delta.hh.
EpsilonClosureOpt
using EpsilonClosureOpt = mata::nfa::EpsilonClosureOpt
Definition at line 21 of file types.hh.
Level
using Level = unsigned
Definition at line 16 of file types.hh.
Limits
using Limits = mata::nfa::Limits
Definition at line 38 of file types.hh.
Move
using Move = mata::nfa::Move
Definition at line 22 of file delta.hh.
ParameterMap
using ParameterMap = mata::nfa::ParameterMap
Map of additional parameter name and value pairs.
Used by certain functions for specifying some additional parameters in the following format:
ParameterMap {
    { "algorithm", "classical" },
    { "minimize", "true" }
}
Definition at line 36 of file types.hh.
ProductFinalStateCondition
using ProductFinalStateCondition = mata::nfa::ProductFinalStateCondition
Definition at line 47 of file types.hh.
Run
using Run = mata::nfa::Run
Definition at line 20 of file types.hh.
State
using State = mata::nfa::State
Definition at line 17 of file types.hh.
StatePost
using StatePost = mata::nfa::StatePost
Definition at line 26 of file delta.hh.
StateRenaming
using StateRenaming = mata::nfa::StateRenaming
Definition at line 23 of file types.hh.
StateSet
using StateSet = mata::nfa::StateSet
Definition at line 18 of file types.hh.
SymbolPost
using SymbolPost = mata::nfa::SymbolPost
Definition at line 24 of file delta.hh.
SynchronizedExistentialSymbolPostIterator
using SynchronizedExistentialSymbolPostIterator = mata::nfa::SynchronizedExistentialSymbolPostIterator
Definition at line 28 of file delta.hh.
Transition
using Transition = mata::nfa::Transition
Definition at line 20 of file delta.hh.
Enumeration Type Documentation
JumpMode
enum class JumpMode strong
A non-deterministic finite transducer.
Enumerator
RepeatSymbol
Repeat the symbol on the jump.
AppendDontCares
Append a sequence of DONT_CAREs to the symbol on the jump.
Definition at line 42 of file types.hh.
Function Documentation
are_equivalent() [1/2]
bool are_equivalent (const Nft & lhs, const Nft & rhs, const Alphabet * alphabet, JumpMode jump_mode = JumpMode::RepeatSymbol, const ParameterMap & params = {{ "algorithm", "antichains"}})
Perform equivalence check of two NFTs: lhs and rhs.
Parameters
[in] lhs First automaton to concatenate.
[in] rhs Second automaton to concatenate.
[in] alphabet Alphabet of both NFTs to compute with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
[in] params[ Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if lhs and rhs are equivalent, false otherwise.
are_equivalent() [2/2]
bool are_equivalent (const Nft & lhs, const Nft & rhs, JumpMode JumpMode = JumpMode::RepeatSymbol, const ParameterMap & params = {{ "algorithm", "antichains"}})
Perform equivalence check of two NFTs: lhs and rhs.
The current implementation of Nft does not accept input alphabet. For this reason, an alphabet has to be created from all transitions each time an operation on alphabet is called. When calling this function, the alphabet has to be computed first.
Hence, this function is less efficient than its alternative taking already defined alphabet as its parameter. That way, alphabet has to be computed only once, as opposed to the current ad-hoc construction of the alphabet. The use of the alternative with defined alphabet should be preferred.
Parameters
[in] lhs First automaton to concatenate.
[in] rhs Second automaton to concatenate.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
[in] params Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if lhs and rhs are equivalent, false otherwise.
complement() [1/2]
Nft complement (const Nft & aut, const Alphabet & alphabet, const ParameterMap & params = {{ "algorithm", "classical" }, { "minimize", "false" }})
Compute automaton accepting complement of aut.
Parameters
[in] aut Automaton whose complement to compute.
[in] alphabet Alphabet used for complementation.
[in] params Optional parameters to control the complementation algorithm:
"algorithm": "classical" (classical algorithm determinizes the automaton, makes it complete and swaps final and non-final states);
"minimize": "true"/"false" (whether to compute minimal deterministic automaton for classical algorithm);
Returns
Complemented automaton.
complement() [2/2]
Nft complement (const Nft & aut, const utils::OrdVector< Symbol > & symbols, const ParameterMap & params = {{ "algorithm", "classical" }, { "minimize", "false" }})
Compute automaton accepting complement of aut.
This overloaded version complements over an already created ordered set of symbols instead of an alphabet. This is a more efficient solution in case you already have symbols precomputed or want to complement multiple automata over the same set of symbols: the function does not need to compute the ordered set of symbols from the alphabet again (and for each automaton).
Parameters
[in] aut Automaton whose complement to compute.
[in] symbols Symbols to complement over.
[in] params Optional parameters to control the complementation algorithm:
"algorithm": "classical" (classical algorithm determinizes the automaton, makes it complete and swaps final and non-final states);
"minimize": "true"/"false" (whether to compute minimal deterministic automaton for classical algorithm);
Returns
Complemented automaton.
compose() [1/2]
Nft compose (const Nft & lhs, const Nft & rhs, const utils::OrdVector< Level > & lhs_sync_levels, const utils::OrdVector< Level > & rhs_sync_levels, bool project_out_sync_levels = true, JumpMode jump_mode = JumpMode::RepeatSymbol)
Composes two NFTs (lhs || rhs; read as "rhs after lhs").
This function computes the composition of two NFTs, lhs and rhs, by aligning their synchronization levels. Transitions between two synchronization levels are ordered as follows: first the transitions of lhs, then the transitions of rhs followed by next synchronization level (if exists). By default, synchronization levels are projected out from the resulting NFT.
Vectors of synchronization levels have to be non-empty and of the the same size.
Parameters
[in] lhs First transducer to compose.
[in] rhs Second transducer to compose.
[in] lhs_sync_levels Ordered vector of synchronization levels of the lhs.
[in] rhs_sync_levels Ordered vector of synchronization levels of the rhs.
[in] project_out_sync_levels Whether we want to project out the synchronization levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE.
Returns
A new NFT after the composition.
compose() [2/2]
Nft compose (const Nft & lhs, const Nft & rhs, Level lhs_sync_level = 1, Level rhs_sync_level = 0, bool project_out_sync_levels = true, JumpMode jump_mode = JumpMode::RepeatSymbol)
Composes two NFTs (lhs || rhs; read as "rhs after lhs").
This function computes the composition of two NFTs, lhs and rhs, by aligning their synchronization levels. Transitions between two synchronization levels are ordered as follows: first the transitions of lhs, then the transitions of rhs followed by next synchronization level (if exists). By default, synchronization levels are projected out from the resulting NFT.
Parameters
[in] lhs First transducer to compose.
[in] rhs Second transducer to compose.
[in] lhs_sync_level The synchronization level of the lhs.
[in] rhs_sync_level The synchronization level of the rhs.
[in] project_out_sync_levels Whether we wont to project out the synchronization levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE.
Returns
A new NFT after the composition.
concatenate()
Nft concatenate (const Nft & lhs, const Nft & rhs, bool use_epsilon = false, StateRenaming * lhs_state_renaming = nullptr, StateRenaming * rhs_state_renaming = nullptr)
Concatenate two NFTs.
Supports epsilon symbols when use_epsilon is set to true.
Parameters
[in] lhs First automaton to concatenate.
[in] rhs Second automaton to concatenate.
[in] use_epsilon Whether to concatenate over epsilon symbol.
[out] lhs_state_renaming Map mapping lhs states to result states.
[out] rhs_state_renaming Map mapping rhs states to result states.
Returns
Concatenated automaton.
determinize()
Nft determinize (const Nft & aut, std::unordered_map< StateSet, State > * subset_map = nullptr)
Determinize automaton.
Parameters
[in] aut Automaton to determinize.
[out] subset_map Map that maps sets of states of input automaton to states of determinized automaton.
Returns
Determinized automaton.
encode_word()
Run encode_word (const Alphabet * alphabet, const std::vector< std::string > & input)
Encodes a vector of strings (each corresponding to one symbol) into a Word instance.
fragile_revert()
Nft fragile_revert (const Nft & aut)
insert_level()
Nft insert_level (const Nft & nft, Level new_level, JumpMode jump_mode = JumpMode::RepeatSymbol)
Inserts a new level new_level into the given transducer nft.
num_of_levels must be greater than 0.
Parameters
[in] nft The original transducer.
[in] new_level Specifies the new level to be inserted into the transducer. If new_level is 0, then it is inserted before the 0-th level. If new_level is less than num_of_levels, then it is inserted before the level new_level-1. If new_level is greater than or equal to num_of_levels, then all levels from num_of_levels through new_level are appended after the last level.
[in] jump_mode Specifies whether the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
insert_levels()
Nft insert_levels (const Nft & nft, const BoolVector & new_levels_mask, JumpMode jump_mode = JumpMode::RepeatSymbol)
Inserts new levels, as specified by the mask new_levels_mask, into the given transducer nft.
num_of_levels must be greater than 0. The vector new_levels_mask must be nonempty, its length must be greater than num_of_levels, and it must contain exactly num_of_levels occurrences of false.
Parameters
[in] nft The original transducer.
[in] new_levels_mask A mask representing the old and new levels. The vector {1, 0, 1, 1, 0} indicates that one level is inserted before level 0 and two levels are inserted before level 1.
[in] jump_mode Specifies whether the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
intersection()
Nft intersection (const Nft & lhs, const Nft & rhs, std::unordered_map< std::pair< State, State >, State > * prod_map = nullptr, JumpMode jump_mode = JumpMode::RepeatSymbol, State lhs_first_aux_state = Limits::max_state, State rhs_first_aux_state = Limits::max_state)
Compute intersection of two NFTs.
Both automata can contain ε-transitions. Epsilons will be handled as alphabet symbols.
Automata must share alphabets. //TODO: this is not implemented yet. Transducers must have equal values of num_of_levels.
Parameters
[in] lhs First NFT to compute intersection for.
[in] rhs Second NFT to compute intersection for.
[out] prod_map Mapping of pairs of the original states (lhs_state, rhs_state) to new product states (not used internally, allocated only when !=nullptr, expensive).
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE.
[in] lhs_first_aux_state The first auxiliary state in lhs. Two auxiliary states does not form a product state.
[in] rhs_first_aux_state The first auxiliary state in rhs. Two auxiliary states does not form a product state.
Returns
NFT as a product of NFTs lhs and rhs.
invert_levels()
Nft invert_levels (const Nft & aut, JumpMode jump_mode = JumpMode::RepeatSymbol)
Inverts the levels of the given transducer aut.
The function inverts the levels of the transducer, i.e., the level 0 becomes the last level, level 1 becomes the second last level, and so on.
Parameters
[in] aut The transducer for inverting levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A new transducer with inverted levels.
is_included() [1/2]
bool is_included (const Nft & smaller, const Nft & bigger, const Alphabet *const alphabet = nullptr, JumpMode jump_mode = JumpMode::RepeatSymbol, const ParameterMap & params = {{ "algorithm", "antichains" }}) inline
Checks inclusion of languages of two NFTs: smaller and bigger (smaller <= bigger).
Parameters
[in] smaller First automaton to concatenate.
[in] bigger Second automaton to concatenate.
[in] alphabet Alphabet of both NFTs to compute with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
[in] params Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if smaller is included in bigger, false otherwise.
Definition at line 944 of file nft.hh.
is_included() [2/2]
bool is_included (const Nft & smaller, const Nft & bigger, Run * cex, const Alphabet * alphabet = nullptr, JumpMode jump_mode = JumpMode::RepeatSymbol, const ParameterMap & params = {{ "algorithm", "antichains" }})
Checks inclusion of languages of two NFTs: smaller and bigger (smaller <= bigger).
Parameters
[in] smaller First automaton to concatenate.
[in] bigger Second automaton to concatenate.
[out] cex Counterexample for the inclusion.
[in] alphabet Alphabet of both NFTs to compute with.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
[in] params Optional parameters to control the equivalence check algorithm:
"algorithm": "naive", "antichains" (Default: "antichains")
Returns
True if smaller is included in bigger, false otherwise.
minimize()
Nft minimize (const Nft & aut, const ParameterMap & params = {{ "algorithm", "brzozowski" }})
Compute minimal deterministic automaton.
Parameters
[in] aut Automaton whose minimal version to compute.
[in] params Optional parameters to control the minimization algorithm:
"algorithm": "brzozowski"
Returns
Minimal deterministic automaton.
Referenced by mata::nft::plumbing::minimize().
product()
Nft product (const Nft & lhs, const Nft & rhs, ProductFinalStateCondition final_condition, Symbol first_epsilon, std::unordered_map< std::pair< State, State >, State > * prod_map) delete
project_out() [1/2]
Nft project_out (const Nft & nft, const utils::OrdVector< Level > & levels_to_project, JumpMode jump_mode = JumpMode::RepeatSymbol)
Projects out specified levels levels_to_project in the given transducer nft.
Parameters
[in] nft The transducer for projection.
[in] levels_to_project A non-empty ordered vector of levels to be projected out from the transducer. It must contain only values that are greater than or equal to 0 and smaller than num_of_levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A new projected transducer.
project_out() [2/2]
Nft project_out (const Nft & nft, Level level_to_project, JumpMode jump_mode = JumpMode::RepeatSymbol)
Projects out specified level level_to_project in the given transducer nft.
Parameters
[in] nft The transducer for projection.
[in] level_to_project A level that is going to be projected out from the transducer. It has to be greater than or equal to 0 and smaller than num_of_levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A new projected transducer.
project_to() [1/2]
Nft project_to (const Nft & nft, const utils::OrdVector< Level > & levels_to_project, JumpMode jump_mode = JumpMode::RepeatSymbol)
Projects to specified levels levels_to_project in the given transducer nft.
Parameters
[in] nft The transducer for projection.
[in] levels_to_project A non-empty ordered vector of levels the transducer is going to be projected to. It must contain only values greater than or equal to 0 and smaller than num_of_levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A new projected transducer.
project_to() [2/2]
Nft project_to (const Nft & nft, Level level_to_project, JumpMode jump_mode = JumpMode::RepeatSymbol)
Projects to a specified level level_to_project in the given transducer nft.
Parameters
[in] nft The transducer for projection.
[in] level_to_project A level the transducer is going to be projected to. It has to be greater than or equal to 0 and smaller than num_of_levels.
[in] jump_mode Specifies if the symbol on a jump transition (a transition with a length greater than 1) is interpreted as a sequence repeating the same symbol or as a single instance of the symbol followed by a sequence of DONT_CARE symbols.
Returns
A new projected transducer.
reduce()
Nft reduce (const Nft & aut, StateRenaming * state_renaming = nullptr, const ParameterMap & params = {{ "algorithm", "simulation" } })
Reduce the size of the automaton.
Parameters
[in] aut Automaton to reduce.
[out] state_renaming Mapping of original states to reduced states.
[in] params Optional parameters to control the reduction algorithm:
"algorithm": "simulation".
Returns
Reduced automaton.
remove_epsilon()
Nft remove_epsilon (const Nft & aut, Symbol epsilon = EPSILON)
Remove simple epsilon transitions.
Simple epsilon transitions are the transitions of the form q0 -epsilon-> q1 -epsilon-> q2 -epsilon-> ... -epsilon-> qn where q0 and qn are level 0 states, the states in-between are states with level 1, 2, ..., num_of_levels and for each qi, for 0 < i < n, there is only 1 transition going to qi (the transition qi-1 -epsilon-> qi) and only 1 transition going from qi (the transition qi -epsilon -> qi+1). This means that if there was some state p0 going with epsilon to q1, these to epsilon transitions would not be removed.
Furthermore, this assumes that the NFT aut does not have jump transitions.
The resulting automaton has the same number of states as aut, just the transitions can change. It is recommended to run trim() after this function.
Parameters
aut NFT without jump transitions
epsilon symbol representing epsilon
Returns
NFT whose language is same as aut but does not contain simple epsilon transitions
Referenced by mata::nft::plumbing::remove_epsilon().
revert()
Nft revert (const Nft & aut)
Referenced by mata::nft::plumbing::revert().
simple_revert()
Nft simple_revert (const Nft & aut)
somewhat_simple_revert()
Nft somewhat_simple_revert (const Nft & aut)
union_det_complete()
Nft union_det_complete (const Nft & lhs, const Nft & rhs) delete
union_nondet()
Nft union_nondet (const Nft & lhs, const Nft & rhs)
Compute non-deterministic union.
Does not add epsilon transitions, just unites initial and final states.
Returns
Non-deterministic union of lhs and rhs.
Referenced by mata::nft::plumbing::union_nondet().
Variable Documentation
DEFAULT_LEVEL
constexpr Level DEFAULT_LEVEL { 0 } constexpr
Definition at line 53 of file types.hh.
DEFAULT_NUM_OF_LEVELS
constexpr Level DEFAULT_NUM_OF_LEVELS { 2 } constexpr
Definition at line 54 of file types.hh.
DONT_CARE
constexpr Symbol DONT_CARE = EPSILON - 1 constexpr
Definition at line 51 of file types.hh.
Referenced by Nft::to_nfa_update_copy(), Nft::to_nfa_update_move(), Nft::unwind_jumps(), Nft::unwind_jumps(), and Nft::unwind_jumps_inplace().
EPSILON
constexpr Symbol EPSILON = mata::nfa::EPSILON constexpr
An epsilon symbol which is now defined as the maximal value of data type used for symbols.
Definition at line 50 of file types.hh.
TYPE_NFT
const std::string TYPE_NFT extern