name: Setup Python environment
description: Setup Python environment for running workflows.
inputs:
  os:
    description: "Operating system to run on"
    required: false
    default: ubuntu-latest
  python-version:
    description: "Python version to run"
    required: true
runs:
  using: "composite"
  steps:
    - name: Add some version to VERSION file (since it cannot be inferred from git)
      shell: bash
      run: echo "0.0.0" > VERSION
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
    - name: Install Python Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        make -C bindings/python init
    - name: Building MacOS dependencies
      if: ${{ inputs.os == 'macos-latest' }}
      shell: bash
      run: brew install graphviz
    - name: Building Unix dependencies
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt -qq update
        sudo apt -qq install -y graphviz graphviz-dev
