name: Setup Python environment
description: Setup Python environment for running workflows.
inputs:
  os:
    description: "Operating system to run on"
    required: false
    default: ubuntu-latest
  python-version:
    description: "Python version to run"
    required: true
  version:
    description: "Version tag to write to the VERSION file (e.g. v1.2.3)."
    required: false
    default: "v0.0.0-dev.1"
runs:
  using: "composite"
  steps:
    - name: Add some version to VERSION file (since it cannot be inferred from git)
      shell: bash
      run: |
        echo "${{ inputs.version }}" > VERSION
        echo "${{ inputs.version }}" > bindings/python/VERSION
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        # cache: "pip"
    - name: Install Python Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        make -C bindings/python init
    - name: Building MacOS dependencies
      if: ${{ inputs.os == 'macos-latest' }}
      shell: bash
      run: brew install graphviz
    - name: Building Unix dependencies
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo apt -qq update
        sudo apt -qq install -y graphviz graphviz-dev
    - name: Install Python Dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel twine
