#ifndef MATA_LAZY_WORD_GENERATOR_HH_
#define MATA_LAZY_WORD_GENERATOR_HH_

#include <generator>
#include <ranges>

#include "mata/alphabet.hh"

namespace mata::utils {

/// Support class for the nfa::plumbing/nft::plumbing get_words_lazy_ptr() functions (the simplified, bindings-facing
///  API). Pull-based adaptor over a @c std::generator<Word>, exposing @c done()/@c next() instead of C++23
///  range-for iteration. Exists for callers that cannot drive a @c std::generator directly — namely the Python
///  bindings, generated by Cython, which has no notion of C++23 coroutines or sentinels — so they can still consume
///  one word at a time instead of materializing the whole sequence.
class LazyWordGenerator {
  public:
	explicit LazyWordGenerator(std::generator<Word> generator)
		: generator_{std::move(generator)},
		  it_{generator_.begin()} {}

	LazyWordGenerator(const LazyWordGenerator&) = delete;
	LazyWordGenerator& operator=(const LazyWordGenerator&) = delete;
	LazyWordGenerator(LazyWordGenerator&&) = delete;
	LazyWordGenerator& operator=(LazyWordGenerator&&) = delete;

	/// True when there are no more words to yield.
	bool done() const { return it_ == std::default_sentinel; }

	/// Return the current word and advance to the next one. @pre !done().
	Word next() {
		Word word{std::move(*it_)};
		++it_;
		return word;
	}

  private:
	std::generator<Word> generator_;
	std::ranges::iterator_t<std::generator<Word>> it_;
};

} // namespace mata::utils

#endif // MATA_LAZY_WORD_GENERATOR_HH_
