name: Code Coverage
on:
  pull_request:
  push:
    # Also run on pushes to the branches PRs are based on, so Codecov has an up-to-date report for the actual
    #  latest commit on the base branch to compare PRs against (see #323).
    branches: [master, devel]
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # fetch-depth: 0
          # If PR, checkout the PR's repo (needed for PRs coming from forks).
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./.github/workflows/actions/setup
      - name: Build library for coverage
        run: make coverage
      - name: Test the library
        run: make test
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          gcov: true
