name: Release (master)
permissions: write-all
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/docs
        with:
          os: ${{ matrix.os }}
  run-tests:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/setup
        with:
          os: ${{ matrix.os }}
      - uses: ./.github/workflows/actions/compile
        with:
          build-log-output-file: "warnings-new"
      - name: Test the library
        run: make test
  run-tests-python:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.13"]
        install-type: ["src", "tarball"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/setup
        with:
          os: ${{ matrix.os }}
      - name: Set up Python and its dependencies ${{ inputs.python-version }}
        uses: ./.github/workflows/actions/setup-python
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
      - name: Write the released version to VERSION file
        shell: bash
        run: echo "v0.0.0-dev.1" > VERSION
      - name: Compile the Python bindings from the tarball
        if: matrix.install-type == 'tarball'
        uses: ./.github/workflows/actions/compile-python-tarball
      - name: Compile the Python bindings from the source
        uses: ./.github/workflows/actions/compile-python-src
      - name: Test the Python bindings
        uses: ./.github/workflows/actions/test-python
  release:
    needs: [build-docs, run-tests, run-tests-python]
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.bump.outputs.new-tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/github-actions-git-config
      - uses: ./.github/workflows/actions/bump-version
        id: bump
  sync-devel-with-master:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/github-actions-git-config
      - name: Merge master into devel
        run: |
          git checkout devel
          git merge origin/master --no-edit
          git push origin devel
  deploy-docs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
  deploy-pypi:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: ./.github/workflows/actions/deploy-pypi
        with:
          os: ${{ runner.os }}
          python-version: ${{ matrix.python-version }}
          version: ${{ needs.release.outputs.new-tag }}
          pypi-token: ${{ secrets.PYPI_SECRET_TOKEN }}
